In [3]:
import os
import re
import string

import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split

from sklearn.metrics import(
    accuracy_score,
    classification_report,
    confusion_matrix
)

from collections import Counter

In [4]:
path = r'Datasets'
csv_path = os.path.join(path,"IMDB Dataset.csv")

df = pd.read_csv(csv_path)

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
print(df.shape)

(50000, 2)

In [6]:
import re

email_pattern = r"[\w.-]+@[\w.-]+\.\w+"
url_pattern = r"https?://\S+\.\S"

URL = re.compile(url_pattern)
EMAIL = re.compile(email_pattern)

In [7]:
# Removal of Stop words

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

nltk.download("stopwords")
nltk.download("punkt")

stop_words = stopwords.words("english")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/mukundanramesh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/mukundanramesh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [8]:
stop_words

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [9]:
def text_clean(cell):
  if not isinstance(cell,str):
    return " "

  cell = EMAIL.sub(" ",cell)
  cell = URL.sub(" ",cell)
  cell = cell.lower()
  cell = re.sub(r"\d+"," ",cell)
  cell = re.sub(r"[^\w\s]","",cell)

  cell = [word for word in cell.split() if word not in stop_words]
  cell = " ".join(cell)

  return cell

df["clean_review"] = df["review"].apply(text_clean)

df.head()

,review,sentiment,clean_review
0,One of the other reviewers has mentioned that ...,positive,one reviewers mentioned watching oz episode yo...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production br br filming tech...
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,basically theres family little boy jake thinks...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...

In [10]:
df["label"] = df["sentiment"].map(
    {
        "positive":1,
        "negative":0
    }
)

df.head()

,review,sentiment,clean_review,label
0,One of the other reviewers has mentioned that ...,positive,one reviewers mentioned watching oz episode yo...,1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production br br filming tech...,1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,1
3,Basically there's a family where a little boy ...,negative,basically theres family little boy jake thinks...,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...,1

In [11]:
train_texts, test_texts, train_labels,test_labels = train_test_split(
    df["clean_review"].values,
    df["label"].values,
    test_size = 0.2,
    random_state = 42
)

print("Train texts shape:",train_texts.shape)
print("Test texts shape:",test_texts.shape)

Train texts shape: (40000,)
Test texts shape: (10000,)

In [12]:
# Build Vocab

MAX_VOCAB_SIZE = 20000

word_counter = Counter()

for text in train_texts:
  words = text.split()
  word_counter.update(words)

most_common_words = word_counter.most_common(
    MAX_VOCAB_SIZE - 2
)

word_to_index = {
    "<PAD>":0,
    "<UNK>":1
}

for word, _ in most_common_words:
  word_to_index[word] = len(word_to_index)


print("Vocabulary size:",len(word_to_index))

Vocabulary size: 20000

In [13]:
print(word_to_index)

{'<PAD>': 0, '<UNK>': 1, 'br': 2, 'movie': 3, 'film': 4, 'one': 5, 'like': 6, 'good': 7, 'even': 8, 'would': 9, 'time': 10, 'really': 11, 'see': 12, 'story': 13, 'much': 14, 'well': 15, 'get': 16, 'also': 17, 'great': 18, 'bad': 19, 'people': 20, 'first': 21, 'dont': 22, 'movies': 23, 'made': 24, 'make': 25, 'could': 26, 'films': 27, 'way': 28, 'characters': 29, 'think': 30, 'watch': 31, 'many': 32, 'seen': 33, 'two': 34, 'character': 35, 'never': 36, 'love': 37, 'acting': 38, 'plot': 39, 'best': 40, 'little': 41, 'know': 42, 'show': 43, 'ever': 44, 'life': 45, 'better': 46, 'still': 47, 'end': 48, 'scene': 49, 'say': 50, 'man': 51, 'scenes': 52, 'something': 53, 'go': 54, 'im': 55, 'back': 56, 'real': 57, 'watching': 58, 'thing': 59, 'doesnt': 60, 'didnt': 61, 'actors': 62, 'years': 63, 'though': 64, 'actually': 65, 'another': 66, 'makes': 67, 'funny': 68, 'find': 69, 'nothing': 70, 'look': 71, 'going': 72, 'lot': 73, 'new': 74, 'every': 75, 'work': 76, 'old': 77, 'us': 78, 'part': 79, 'director': 80, 'cant': 81, 'thats': 82, 'things': 83, 'quite': 84, 'want': 85, 'cast': 86, 'pretty': 87, 'seems': 88, 'around': 89, 'got': 90, 'take': 91, 'young': 92, 'world': 93, 'fact': 94, 'however': 95, 'enough': 96, 'thought': 97, 'give': 98, 'ive': 99, 'big': 100, 'horror': 101, 'may': 102, 'without': 103, 'long': 104, 'isnt': 105, 'saw': 106, 'always': 107, 'original': 108, 'gets': 109, 'almost': 110, 'music': 111, 'right': 112, 'must': 113, 'series': 114, 'come': 115, 'whole': 116, 'least': 117, 'theres': 118, 'times': 119, 'interesting': 120, 'role': 121, 'comedy': 122, 'guy': 123, 'point': 124, 'action': 125, 'done': 126, 'far': 127, 'bit': 128, 'feel': 129, 'minutes': 130, 'might': 131, 'script': 132, 'anything': 133, 'since': 134, 'hes': 135, 'probably': 136, 'last': 137, 'family': 138, 'kind': 139, 'performance': 140, 'worst': 141, 'tv': 142, 'away': 143, 'yet': 144, 'rather': 145, 'anyone': 146, 'fun': 147, 'sure': 148, 'found': 149, 'making': 150, 'played': 151, 'girl': 152, 'although': 153, 'believe': 154, 'shows': 155, 'trying': 156, 'woman': 157, 'course': 158, 'hard': 159, 'especially': 160, 'comes': 161, 'put': 162, 'goes': 163, 'everything': 164, 'day': 165, 'main': 166, 'worth': 167, 'dvd': 168, 'maybe': 169, 'looking': 170, 'different': 171, 'ending': 172, 'place': 173, 'watched': 174, 'wasnt': 175, 'looks': 176, 'effects': 177, 'book': 178, 'sense': 179, 'set': 180, 'reason': 181, 'three': 182, 'someone': 183, 'screen': 184, 'true': 185, 'money': 186, 'job': 187, 'plays': 188, 'play': 189, 'takes': 190, 'special': 191, 'everyone': 192, 'together': 193, 'said': 194, 'actor': 195, 'instead': 196, 'seem': 197, 'later': 198, 'left': 199, 'seeing': 200, 'american': 201, 'beautiful': 202, 'audience': 203, 'excellent': 204, 'john': 205, 'war': 206, 'night': 207, 'version': 208, 'shot': 209, 'idea': 210, 'house': 211, 'high': 212, 'fan': 213, 'simply': 214, 'black': 215, 'youre': 216, 'nice': 217, 'completely': 218, 'used': 219, 'poor': 220, 'death': 221, 'read': 222, 'kids': 223, 'short': 224, 'second': 225, 'wife': 226, 'friends': 227, 'along': 228, 'else': 229, 'year': 230, 'help': 231, 'try': 232, 'men': 233, 'boring': 234, 'need': 235, 'star': 236, 'given': 237, 'home': 238, 'mind': 239, 'enjoy': 240, 'use': 241, 'either': 242, 'half': 243, 'less': 244, 'rest': 245, 'truly': 246, 'performances': 247, 'classic': 248, 'dead': 249, 'next': 250, 'production': 251, 'recommend': 252, 'couple': 253, 'father': 254, 'wrong': 255, 'tell': 256, 'stupid': 257, 'line': 258, 'came': 259, 'let': 260, 'start': 261, 'hollywood': 262, 'full': 263, 'understand': 264, 'women': 265, 'perhaps': 266, 'getting': 267, 'terrible': 268, 'mean': 269, 'remember': 270, 'keep': 271, 'camera': 272, 'wonderful': 273, 'school': 274, 'others': 275, 'moments': 276, 'awful': 277, 'sex': 278, 'episode': 279, 'definitely': 280, 'name': 281, 'video': 282, 'human': 283, 'gives': 284, 'early': 285, 'budget': 286, 'playing': 287, 'often': 288, 'small': 289, 'top': 290, 'couldnt': 291, 'person': 292, 'perfect': 293, 'finally': 294, 'dialogue': 295, 'went': 296, 'certainly': 297, 'stars': 298, 'lines': 299, 'absolutely': 300, 'guys': 301, 'liked': 302, 'face': 303, 'case': 304, 'piece': 305, 'head': 306, 'title': 307, 'sort': 308, 'hope': 309, 'loved': 310, 'become': 311, 'several': 312, 'written': 313, 'entire': 314, 'supposed': 315, 'mother': 316, 'style': 317, 'lost': 318, 'felt': 319, 'overall': 320, 'yes': 321, 'live': 322, 'sound': 323, 'worse': 324, 'entertaining': 325, 'problem': 326, 'oh': 327, 'boy': 328, 'totally': 329, 'waste': 330, 'laugh': 331, 'based': 332, 'friend': 333, 'seemed': 334, 'picture': 335, 'wanted': 336, 'mr': 337, 'beginning': 338, 'shes': 339, 'care': 340, 'youll': 341, 'dark': 342, 'cinema': 343, 'id': 344, 'direction': 345, 'final': 346, 'despite': 347, 'fans': 348, 'already': 349, 'humor': 350, 'becomes': 351, 'turn': 352, 'lead': 353, 'throughout': 354, 'evil': 355, 'example': 356, 'wont': 357, 'game': 358, 'children': 359, 'lives': 360, 'low': 361, 'guess': 362, 'unfortunately': 363, 'called': 364, 'able': 365, 'days': 366, 'girls': 367, 'wants': 368, 'drama': 369, 'fine': 370, 'quality': 371, 'white': 372, 'writing': 373, 'enjoyed': 374, 'kill': 375, 'horrible': 376, 'history': 377, 'tries': 378, 'amazing': 379, 'michael': 380, 'gave': 381, 'theyre': 382, 'killer': 383, 'works': 384, 'turns': 385, 'act': 386, 'son': 387, 'matter': 388, 'behind': 389, 'side': 390, 'expect': 391, 'favorite': 392, 'past': 393, 'flick': 394, 'brilliant': 395, 'parts': 396, 'eyes': 397, 'obviously': 398, 'run': 399, 'says': 400, 'ones': 401, 'killed': 402, 'directed': 403, 'viewer': 404, 'starts': 405, 'town': 406, 'car': 407, 'group': 408, 'highly': 409, 'decent': 410, 'heard': 411, 'soon': 412, 'thinking': 413, 'sometimes': 414, 'actress': 415, 'stuff': 416, 'heart': 417, 'ill': 418, 'late': 419, 'took': 420, 'kid': 421, 'art': 422, 'city': 423, 'genre': 424, 'happens': 425, 'hell': 426, 'except': 427, 'leave': 428, 'child': 429, 'wouldnt': 430, 'hour': 431, 'feeling': 432, 'fight': 433, 'extremely': 434, 'told': 435, 'etc': 436, 'cannot': 437, 'lack': 438, 'wonder': 439, 'save': 440, 'blood': 441, 'close': 442, 'including': 443, 'looked': 444, 'police': 445, 'score': 446, 'strong': 447, 'ok': 448, 'particularly': 449, 'stories': 450, 'shown': 451, 'coming': 452, 'moment': 453, 'attempt': 454, 'obvious': 455, 'anyway': 456, 'itbr': 457, 'involved': 458, 'hand': 459, 'experience': 460, 'daughter': 461, 'living': 462, 'happen': 463, 'complete': 464, 'taken': 465, 'type': 466, 'violence': 467, 'stop': 468, 'chance': 469, 'james': 470, 'happened': 471, 'simple': 472, 'god': 473, 'serious': 474, 'cool': 475, 'opening': 476, 'song': 477, 'please': 478, 'murder': 479, 'usually': 480, 'robert': 481, 'across': 482, 'number': 483, 'known': 484, 'roles': 485, 'david': 486, 'ago': 487, 'released': 488, 'hours': 489, 'hilarious': 490, 'voice': 491, 'order': 492, 'exactly': 493, 'huge': 494, 'english': 495, 'saying': 496, 'lets': 497, 'cinematography': 498, 'interest': 499, 'jokes': 500, 'possible': 501, 'whose': 502, 'slow': 503, 'none': 504, 'wish': 505, 'talent': 506, 'crap': 507, 'age': 508, 'seriously': 509, 'started': 510, 'cut': 511, 'running': 512, 'relationship': 513, 'sad': 514, 'brother': 515, 'alone': 516, 'major': 517, 'shots': 518, 'gore': 519, 'taking': 520, 'ridiculous': 521, 'reality': 522, 'female': 523, 'today': 524, 'beyond': 525, 'somewhat': 526, 'annoying': 527, 'hit': 528, 'view': 529, 'call': 530, 'ends': 531, 'change': 532, 'career': 533, 'important': 534, 'knew': 535, 'documentary': 536, 'turned': 537, 'strange': 538, 'body': 539, 'rating': 540, 'power': 541, 'scary': 542, 'hero': 543, 'usual': 544, 'basically': 545, 'mostly': 546, 'apparently': 547, 'episodes': 548, 'opinion': 549, 'word': 550, 'finds': 551, 'silly': 552, 'husband': 553, 'upon': 554, 'words': 555, 'due': 556, 'knows': 557, 'talking': 558, 'novel': 559, 'whats': 560, 'four': 561, 'british': 562, 'country': 563, 'happy': 564, 'problems': 565, 'clearly': 566, 'attention': 567, 'arent': 568, 'moviebr': 569, 'single': 570, 'musical': 571, 'directors': 572, 'local': 573, 'miss': 574, 'add': 575, 'room': 576, 'jack': 577, 'disappointed': 578, 'tells': 579, 'level': 580, 'events': 581, 'talk': 582, 'cheap': 583, 'light': 584, 'modern': 585, 'television': 586, 'songs': 587, 'sequence': 588, 'predictable': 589, 'whether': 590, 'review': 591, 'appears': 592, 'supporting': 593, 'easily': 594, 'dialog': 595, 'sets': 596, 'havent': 597, 'lots': 598, 'falls': 599, 'giving': 600, 'ten': 601, 'five': 602, 'soundtrack': 603, 'tried': 604, 'space': 605, 'moving': 606, 'similar': 607, 'mention': 608, 'bring': 609, 'within': 610, 'team': 611, 'needs': 612, 'enjoyable': 613, 'future': 614, 'parents': 615, 'certain': 616, 'french': 617, 'romantic': 618, 'bunch': 619, 'viewers': 620, 'filmbr': 621, 'entertainment': 622, 'storyline': 623, 'showing': 624, 'hate': 625, 'surprised': 626, 'filmed': 627, 'dull': 628, 'george': 629, 'middle': 630, 'among': 631, 'clear': 632, 'earth': 633, 'theme': 634, 'subject': 635, 'stay': 636, 'message': 637, 'thriller': 638, 'named': 639, 'fall': 640, 'using': 641, 'easy': 642, 'typical': 643, 'king': 644, 'sorry': 645, 'sequel': 646, 'comments': 647, 'greatest': 648, 'feels': 649, 'nearly': 650, 'kept': 651, 'release': 652, 'working': 653, 'theater': 654, 'ways': 655, 'elements': 656, 'effort': 657, 'buy': 658, 'near': 659, 'deal': 660, 'tale': 661, 'writer': 662, 'means': 663, 'avoid': 664, 'th': 665, 'brought': 666, 'youve': 667, 'class': 668, 'doubt': 669, 'actual': 670, 'straight': 671, 'realistic': 672, 'boys': 673, 'suspense': 674, 'editing': 675, 'famous': 676, 'comic': 677, 'sister': 678, 'gone': 679, 'richard': 680, 'feature': 681, 'rock': 682, 'reviews': 683, 'learn': 684, 'die': 685, 'lady': 686, 'dr': 687, 'general': 688, 'points': 689, 'imagine': 690, 'leads': 691, 'minute': 692, 'move': 693, 'check': 694, 'peter': 695, 'somehow': 696, 'begins': 697, 'monster': 698, 'whos': 699, 'material': 700, 'fantastic': 701, 'hear': 702, 'forget': 703, 'particular': 704, 'okay': 705, 'viewing': 706, 'weak': 707, 'form': 708, 'crime': 709, 'animation': 710, 'figure': 711, 'sequences': 712, 'mystery': 713, 'rent': 714, 'deep': 715, 'decided': 716, 'sit': 717, 'premise': 718, 'killing': 719, 'eventually': 720, 'tom': 721, 'atmosphere': 722, 'fast': 723, 'period': 724, 'surprise': 725, 'paul': 726, 'believable': 727, 'emotional': 728, 'forced': 729, 'red': 730, 'expected': 731, 'shame': 732, 'truth': 733, 'dog': 734, 'follow': 735, 'difficult': 736, 'poorly': 737, 'wait': 738, 'indeed': 739, 'eye': 740, 'became': 741, 'crew': 742, 'whatever': 743, 'scifi': 744, 'season': 745, 'memorable': 746, 'average': 747, 'lame': 748, 'york': 749, 'leaves': 750, 'doctor': 751, 'possibly': 752, 'situation': 753, 'dance': 754, 'stand': 755, 'needed': 756, 'open': 757, 'interested': 758, 'cheesy': 759, 'superb': 760, 'credits': 761, 'meets': 762, 'reading': 763, 'begin': 764, 'unless': 765, 'note': 766, 'nature': 767, 'sexual': 768, 'filmmakers': 769, 'footage': 770, 'write': 771, 'imdb': 772, 'writers': 773, 'plus': 774, 'otherwise': 775, 'third': 776, 'western': 777, 'incredibly': 778, 'question': 779, 'features': 780, 'gay': 781, 'meet': 782, 'hands': 783, 'male': 784, 'romance': 785, 'towards': 786, 'oscar': 787, 'earlier': 788, 'beauty': 789, 'personal': 790, 'previous': 791, 'keeps': 792, 'inside': 793, 'quickly': 794, 'box': 795, 'society': 796, 'hot': 797, 'sounds': 798, 'copy': 799, 'result': 800, 'badly': 801, 'unique': 802, 'total': 803, 'realize': 804, 'b': 805, 'screenplay': 806, 'setting': 807, 'battle': 808, 'weird': 809, 'japanese': 810, 'laughs': 811, 'background': 812, 'comment': 813, 'effect': 814, 'following': 815, 'ask': 816, 'powerful': 817, 'appear': 818, 'directing': 819, 'various': 820, 'worked': 821, 'older': 822, 'america': 823, 'masterpiece': 824, 'street': 825, 'air': 826, 'island': 827, 'free': 828, 'perfectly': 829, 'portrayed': 830, 'de': 831, 'lee': 832, 'water': 833, 'plenty': 834, 'development': 835, 'brings': 836, 'admit': 837, 'joe': 838, 'acted': 839, 'stage': 840, 'mark': 841, 'outside': 842, 'fairly': 843, 'spent': 844, 'forward': 845, 'dumb': 846, 'meant': 847, 'front': 848, 'baby': 849, 'deserves': 850, 'attempts': 851, 'remake': 852, 'creepy': 853, 'create': 854, 'manages': 855, 'apart': 856, 'bill': 857, 'expecting': 858, 'business': 859, 'agree': 860, 'joke': 861, 'leading': 862, 'wasted': 863, 'caught': 864, 'hardly': 865, 'dramatic': 866, 'crazy': 867, 'cover': 868, 'ideas': 869, 'fails': 870, 'reasons': 871, 'brothers': 872, 'fire': 873, 'present': 874, 'missing': 875, 'mess': 876, 'party': 877, 'political': 878, 'secret': 879, 'rich': 880, 'pay': 881, 'girlfriend': 882, 'plain': 883, 'odd': 884, 'potential': 885, 'members': 886, 'return': 887, 'william': 888, 'large': 889, 'unlike': 890, 'twist': 891, 'talented': 892, 'clever': 893, 'laughing': 894, 'fighting': 895, 'recently': 896, 'telling': 897, 'cute': 898, 'zombie': 899, 'cop': 900, 'la': 901, 'success': 902, 'dream': 903, 'break': 904, 'pure': 905, 'match': 906, 'gun': 907, 'missed': 908, 'slightly': 909, 'created': 910, 'casting': 911, 'sadly': 912, 'sees': 913, 'hold': 914, 'cause': 915, 'uses': 916, 'villain': 917, 'ended': 918, 'incredible': 919, 'disney': 920, 'escape': 921, 'decides': 922, 'public': 923, 'visual': 924, 'married': 925, 'pace': 926, 'considering': 927, 'waiting': 928, 'produced': 929, 'died': 930, 'german': 931, 'familiar': 932, 'nudity': 933, 'cartoon': 934, 'speak': 935, 'state': 936, 'mentioned': 937, 'intelligent': 938, 'credit': 939, 'popular': 940, 'portrayal': 941, 'biggest': 942, 'amount': 943, 'list': 944, 'flat': 945, 'office': 946, 'rate': 947, 'younger': 948, 'fantasy': 949, 'appreciate': 950, 'former': 951, 'entirely': 952, 'italian': 953, 'dancing': 954, 'fit': 955, 'wrote': 956, 'convincing': 957, 'suddenly': 958, 'train': 959, 'company': 960, 'follows': 961, 'compared': 962, 'era': 963, 'van': 964, 'spend': 965, 'neither': 966, 'common': 967, 'moves': 968, 'fear': 969, 'hair': 970, 'trouble': 971, 'scott': 972, 'filled': 973, 'producers': 974, 'sick': 975, 'ultimately': 976, 'successful': 977, 'kills': 978, 'violent': 979, 'exciting': 980, 'value': 981, 'language': 982, 'audiences': 983, 'bizarre': 984, 'science': 985, 'longer': 986, 'store': 987, 'focus': 988, 'basic': 989, 'century': 990, 'mad': 991, 'sweet': 992, 'bored': 993, 'college': 994, 'social': 995, 'positive': 996, 'images': 997, 'concept': 998, 'alive': 999, 'recent': 1000, 'tension': 1001, 'recommended': 1002, 'questions': 1003, 'band': 1004, 'force': 1005, 'honest': 1006, 'situations': 1007, 'leaving': 1008, 'cold': 1009, 'pointless': 1010, 'singing': 1011, 'yeah': 1012, 'alien': 1013, 'aside': 1014, 'choice': 1015, 'decide': 1016, 'consider': 1017, 'barely': 1018, 'project': 1019, 'awesome': 1020, 'involving': 1021, 'amusing': 1022, 'respect': 1023, 'impressive': 1024, 'spirit': 1025, 'christmas': 1026, 'likes': 1027, 'showed': 1028, 'depth': 1029, 'werent': 1030, 'control': 1031, 'fake': 1032, 'soldiers': 1033, 'thanks': 1034, 'considered': 1035, 'charles': 1036, 'effective': 1037, 'impossible': 1038, 'changed': 1039, 'values': 1040, 'immediately': 1041, 'somewhere': 1042, 'revenge': 1043, 'books': 1044, 'solid': 1045, 'bought': 1046, 'humour': 1047, 'studio': 1048, 'pathetic': 1049, 'shooting': 1050, 'meaning': 1051, 'walk': 1052, 'normal': 1053, 'honestly': 1054, 'accent': 1055, 'adult': 1056, 'sitting': 1057, 'thinks': 1058, 'master': 1059, 'culture': 1060, 'jane': 1061, 'explain': 1062, 'channel': 1063, 'garbage': 1064, 'gang': 1065, 'surprisingly': 1066, 'literally': 1067, 'chemistry': 1068, 'failed': 1069, 'touch': 1070, 'fair': 1071, 'ben': 1072, 'ability': 1073, 'disturbing': 1074, 'pick': 1075, 'camp': 1076, 'runs': 1077, 'vampire': 1078, 'trash': 1079, 'cat': 1080, 'army': 1081, 'brain': 1082, 'tone': 1083, 'genius': 1084, 'likely': 1085, 'road': 1086, 'starring': 1087, 'aspect': 1088, 'blue': 1089, 'issues': 1090, 'added': 1091, 'bother': 1092, 'glad': 1093, 'slasher': 1094, 'remains': 1095, 'journey': 1096, 'twists': 1097, 'nobody': 1098, 'jim': 1099, 'week': 1100, 'sexy': 1101, 'conclusion': 1102, 'beautifully': 1103, 'spoilers': 1104, 'adventure': 1105, 'trip': 1106, 'drug': 1107, 'personally': 1108, 'west': 1109, 'south': 1110, 'terms': 1111, 'bed': 1112, 'prison': 1113, 'generally': 1114, 'purpose': 1115, 'managed': 1116, 'shoot': 1117, 'subtle': 1118, 'animated': 1119, 'stick': 1120, 'charming': 1121, 'fiction': 1122, 'utterly': 1123, 'standard': 1124, 'appearance': 1125, 'giant': 1126, 'park': 1127, 'mood': 1128, 'cinematic': 1129, 'silent': 1130, 'nowhere': 1131, 'win': 1132, 'lovely': 1133, 'thrown': 1134, 'complex': 1135, 'loves': 1136, 'military': 1137, 'available': 1138, 'changes': 1139, 'zombies': 1140, 'plan': 1141, 'steve': 1142, 'chase': 1143, 'naked': 1144, 'ghost': 1145, 'edge': 1146, 'natural': 1147, 'cult': 1148, 'walking': 1149, 'pictures': 1150, 'chris': 1151, 'tough': 1152, 'indian': 1153, 'constantly': 1154, 'presence': 1155, 'historical': 1156, 'planet': 1157, 'frank': 1158, 'photography': 1159, 'emotions': 1160, 'details': 1161, 'taste': 1162, 'attack': 1163, 'innocent': 1164, 'land': 1165, 'catch': 1166, 'government': 1167, 'knowing': 1168, 'soul': 1169, 'appeal': 1170, 'door': 1171, 'computer': 1172, 'terrific': 1173, 'jones': 1174, 'makers': 1175, 'dad': 1176, 'touching': 1177, 'places': 1178, 'slowly': 1179, 'bottom': 1180, 'scenery': 1181, 'contains': 1182, 'adaptation': 1183, 'smart': 1184, 'pieces': 1185, 'suppose': 1186, 'feelings': 1187, 'thank': 1188, 'puts': 1189, 'minor': 1190, 'costumes': 1191, 'track': 1192, 'sent': 1193, 'ride': 1194, 'stands': 1195, 'impression': 1196, 'hey': 1197, 'besides': 1198, 'mysterious': 1199, 'excuse': 1200, 'presented': 1201, 'london': 1202, 'pass': 1203, 'narrative': 1204, 'intended': 1205, 'unbelievable': 1206, 'detective': 1207, 'date': 1208, 'painful': 1209, 'critics': 1210, 'rare': 1211, 'names': 1212, 'equally': 1213, 'sam': 1214, 'magic': 1215, 'disappointing': 1216, 'laughable': 1217, 'thus': 1218, 'everybody': 1219, 'acts': 1220, 'building': 1221, 'wild': 1222, 'surely': 1223, 'self': 1224, 'brief': 1225, 'comedies': 1226, 'notice': 1227, 'mary': 1228, 'hoping': 1229, 'stunning': 1230, 'filming': 1231, 'outstanding': 1232, 'makeup': 1233, 'central': 1234, 'law': 1235, 'fully': 1236, 'tired': 1237, 'finish': 1238, 'youd': 1239, 'loud': 1240, 'climax': 1241, 'paris': 1242, 'hospital': 1243, 'mainly': 1244, 'students': 1245, 'finding': 1246, 'st': 1247, 'image': 1248, 'wow': 1249, 'festival': 1250, 'aspects': 1251, 'offer': 1252, 'themes': 1253, 'producer': 1254, 'boyfriend': 1255, 'mistake': 1256, 'forever': 1257, 'ray': 1258, 'bond': 1259, 'woods': 1260, 'tony': 1261, 'support': 1262, 'opportunity': 1263, 'pain': 1264, 'student': 1265, 'opera': 1266, 'suggest': 1267, 'ed': 1268, 'bruce': 1269, 'emotion': 1270, 'throw': 1271, 'charm': 1272, 'race': 1273, 'manner': 1274, 'random': 1275, 'club': 1276, 'christopher': 1277, 'laughed': 1278, 'confusing': 1279, 'mans': 1280, 'million': 1281, 'victims': 1282, 'hurt': 1283, 'expectations': 1284, 'fresh': 1285, 'dreams': 1286, 'confused': 1287, 'green': 1288, 'speaking': 1289, 'faces': 1290, 'cops': 1291, 'victim': 1292, 'pull': 1293, 'award': 1294, 'lived': 1295, 'fascinating': 1296, 'supposedly': 1297, 'spoiler': 1298, 'likable': 1299, 'location': 1300, 'include': 1301, 'answer': 1302, 'batman': 1303, 'seemingly': 1304, 'disappointment': 1305, 'radio': 1306, 'affair': 1307, 'charlie': 1308, 'grade': 1309, 'content': 1310, 'lacks': 1311, 'holes': 1312, 'drugs': 1313, 'vs': 1314, 'boss': 1315, 'news': 1316, 'rated': 1317, 'agent': 1318, 'helps': 1319, 'twice': 1320, 'compelling': 1321, 'wondering': 1322, 'reminded': 1323, 'born': 1324, 'summer': 1325, 'fell': 1326, 'difference': 1327, 'cry': 1328, 'lighting': 1329, 'creative': 1330, 

In [14]:
# Tokenize and pad

MAX_LENGTH = 250

def encode_text(text):
  words = text.split()

  encode = [
      word_to_index.get(word,1) for word in words
  ]

  encode = encode[:MAX_LENGTH]

  if len(encode) < MAX_LENGTH:
    encode = encode + [0] * (MAX_LENGTH - len(encode))

  return encode

example = "this movie good"

print(encode_text(example)[:10])

[1, 3, 7, 0, 0, 0, 0, 0, 0, 0]

In [15]:
class IMDBDataset(Dataset):
  def __init__(self,texts,labels):
    self.texts = texts
    self.labels = labels

  def __len__(self):
    return len(self.texts)

  def __getitem__(self,idx):
    text = self.texts[idx]
    label = self.labels[idx]

    encoded_text = encode_text(text)
    return torch.tensor(encoded_text),torch.tensor(label)

train_dataset = IMDBDataset(train_texts,train_labels)
test_dataset = IMDBDataset(test_texts,test_labels)

In [16]:
train_loader = DataLoader(train_dataset,batch_size=64,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=64,shuffle=False)