In [4]:
import pandas as pd

# ==========================================================
# Problem 1: Department Salary Report
#
# Business Requirement:
#
# Find the average salary of employees
# in each department.
#
# Expected Output:
# Department | Average Salary
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank"],
    "Department":["HR","IT","IT","HR","Finance","Finance"],
    "Salary":[50000,70000,80000,55000,90000,85000]
})

df.groupby('Department').agg(Average_Salary=('Salary', 'mean'))

            Average_Salary
Department
Finance            87500.0
HR                 52500.0
IT                 75000.0

In [2]:
import pandas as pd

# ==========================================================
# Problem 2: Store Sales Analysis
#
# Business Requirement:
#
# Calculate the total sales generated
# by each store.
#
# Sort the result in descending order
# of total sales.
# ==========================================================

df = pd.DataFrame({
    "Store":["A","A","B","B","C","C","A","C"],
    "Sales":[120,80,150,130,90,110,100,95]
})

df.groupby('Store').sum().sort_values(by='Sales', ascending=False)

       Sales
Store
A        300
C        295
B        280