In [4]:
import pandas as pd

# ==========================================================
# Problem 1: Department Salary Report
#
# Business Requirement:
#
# Find the average salary of employees
# in each department.
#
# Expected Output:
# Department | Average Salary
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank"],
    "Department":["HR","IT","IT","HR","Finance","Finance"],
    "Salary":[50000,70000,80000,55000,90000,85000]
})

df.groupby('Department').agg(Average_Salary=('Salary', 'mean'))

            Average_Salary
Department
Finance            87500.0
HR                 52500.0
IT                 75000.0

In [2]:
import pandas as pd

# ==========================================================
# Problem 2: Store Sales Analysis
#
# Business Requirement:
#
# Calculate the total sales generated
# by each store.
#
# Sort the result in descending order
# of total sales.
# ==========================================================

df = pd.DataFrame({
    "Store":["A","A","B","B","C","C","A","C"],
    "Sales":[120,80,150,130,90,110,100,95]
})

df.groupby('Store').sum().sort_values(by='Sales', ascending=False)

       Sales
Store
A        300
C        295
B        280

In [3]:
import pandas as pd

# ==========================================================
# Problem 3: Student Performance
#
# Business Requirement:
#
# Find the average marks obtained
# in each subject.
#
# Also display the highest marks
# in each subject.
# ==========================================================

df = pd.DataFrame({
    "Student":["A","B","C","D","E","F","G","H"],
    "Subject":["Math","Math","Science","Science",
               "English","English","Math","Science"],
    "Marks":[88,92,75,84,90,86,95,81]
})

df.groupby('Subject').agg(
    Average_mark=('Marks','mean'),
    Highest_mark=('Marks','max')
)

         Average_mark  Highest_mark
Subject
English     88.000000            90
Math        91.666667            95
Science     80.000000            84

In [5]:
import pandas as pd

# ==========================================================
# Problem 4: Company Employee Analytics
#
# Business Requirement:
#
# For each department,
# calculate:
#
# • Average Salary
# • Maximum Salary
# • Minimum Salary
# • Number of Employees
#
# Rename the output columns to:
#
# Average Salary
# Highest Salary
# Lowest Salary
# Employee Count
# ==========================================================

df = pd.DataFrame({
    "Department":["IT","IT","HR","HR",
                  "Finance","Finance","Marketing"],
    "Employee":["John","Alice","Bob","Sara",
                "Mike","Eva","Tom"],
    "Salary":[70000,85000,55000,60000,
              90000,95000,65000]
})

df.groupby('Department').agg(
    Average_salary=('Salary','mean'),
    Maximum_Salary=('Salary','max'),
    Minimum_Salary=('Salary','min'),
    Number_of_employees = ('Employee','count')
).rename(columns={'Average_salary':"Average Salary",
                  "Maximum_Salary":"Highest Salary",
                  "Minimum_Salary":"Lowest Salary",
                  "Number_of_employees":"Employee Count"})

            Average Salary  Highest Salary  Lowest Salary  Employee Count
Department
Finance            92500.0           95000          90000               2
HR                 57500.0           60000          55000               2
IT                 77500.0           85000          70000               2
Marketing          65000.0           65000          65000               1