In [3]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r'/Users/mukundanramesh/projects/ai_ml_course_bootcamp_practice/ai-ml-course-bootcamp/Pandas/datasets/cumulative.csv',index_col=0)
df.head(5)

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
rowid,,,,,,,,,,,,,,,,,,,,,
1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

1. Structure and quality

How many rows and columns does the dataset have, and what are the dtypes?
Which columns have missing values, and what percentage is missing in each?
Are there duplicate rows, or duplicate kepid/kepoi_name entries?
Which columns are essentially "ID" columns (won't be useful as features)?

In [25]:
#How many rows and columns does the dataset have, and what are the dtypes?
shape = df.shape
print(f"THe dataset has {shape[0]} rows and {shape[1]} columns")
print(df.describe())

THe dataset has 9564 rows and 49 columns
              kepid    koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
count  9.564000e+03  8054.000000    9564.000000    9564.000000    9564.000000
mean   7.690628e+06     0.480829       0.188206       0.231598       0.194898
std    2.653459e+06     0.476928       0.390897       0.421875       0.396143
min    7.574500e+05     0.000000       0.000000       0.000000       0.000000
25%    5.556034e+06     0.000000       0.000000       0.000000       0.000000
50%    7.906892e+06     0.334000       0.000000       0.000000       0.000000
75%    9.873066e+06     0.998000       0.000000       0.000000       0.000000
max    1.293514e+07     1.000000       1.000000       1.000000       1.000000

       koi_fpflag_ec     koi_period  koi_period_err1  koi_period_err2  \
count    9564.000000    9564.000000      9110.000000      9110.000000
mean        0.120033      75.671358         0.002148        -0.002148
std         0.325018    1334.744046         0.008236         0.008236
min         0.000000       0.241843         0.000000        -0.172500
25%         0.000000       2.733684         0.000005        -0.000276
50%         0.000000       9.752831         0.000035        -0.000035
75%         0.000000      40.715178         0.000276        -0.000005
max         1.000000  129995.778400         0.172500         0.000000

       koi_time0bk  ...  koi_steff_err2    koi_slogg  koi_slogg_err1  \
count  9564.000000  ...     9081.000000  9201.000000     9096.000000
mean    166.183251  ...     -162.265059     4.310157        0.120738
std      67.918960  ...       72.746348     0.432606        0.132837
min     120.515914  ...    -1762.000000     0.047000        0.000000
25%     132.761718  ...     -198.000000     4.218000        0.042000
50%     137.224595  ...     -160.000000     4.438000        0.070000
75%     170.694603  ...     -114.000000     4.543000        0.149000
max    1472.522306  ...        0.000000     5.364000        1.472000

       koi_slogg_err2     koi_srad  koi_srad_err1  koi_srad_err2           ra  \
count     9096.000000  9201.000000    9096.000000    9096.000000  9564.000000
mean        -0.143161     1.728712       0.362292      -0.394806   292.060163
std          0.085477     6.127185       0.930870       2.168213     4.766657
min         -1.207000     0.109000       0.000000    -116.137000   279.852720
25%         -0.196000     0.829000       0.129000      -0.250000   288.660770
50%         -0.128000     1.000000       0.251000      -0.111000   292.261125
75%         -0.088000     1.345000       0.364000      -0.069000   295.859160
max          0.000000   229.908000      33.091000       0.000000   301.720760

               dec   koi_kepmag
count  9564.000000  9563.000000
mean     43.810433    14.264606
std       3.601243     1.385448
min      36.577381     6.966000
25%      40.777173    13.440000
50%      43.677504    14.520000
75%      46.714611    15.322000
max      52.336010    20.003000

[8 rows x 44 columns]

In [28]:
#Which columns have missing values, and what percentage is missing in each?
missing = (df.isna().mean() * 100).round(2)
missing[missing > 0].sort_values(ascending=False)

koi_teq_err1         100.00
koi_teq_err2         100.00
kepler_name           76.01
koi_score             15.79
koi_steff_err2         5.05
koi_srad_err2          4.89
koi_srad_err1          4.89
koi_slogg_err2         4.89
koi_slogg_err1         4.89
koi_steff_err1         4.89
koi_period_err2        4.75
koi_depth_err2         4.75
koi_time0bk_err1       4.75
koi_period_err1        4.75
koi_impact_err2        4.75
koi_depth_err1         4.75
koi_time0bk_err2       4.75
koi_impact_err1        4.75
koi_duration_err2      4.75
koi_duration_err1      4.75
koi_prad               3.80
koi_prad_err2          3.80
koi_teq                3.80
koi_depth              3.80
koi_impact             3.80
koi_srad               3.80
koi_model_snr          3.80
koi_prad_err1          3.80
koi_steff              3.80
koi_slogg              3.80
koi_tce_delivname      3.62
koi_tce_plnt_num       3.62
koi_insol_err2         3.36
koi_insol_err1         3.36
koi_insol              3.36
koi_kepmag             0.01
dtype: float64

In [31]:
#Are there duplicate rows, or duplicate kepid/kepoi_name entries?
df.duplicated(subset=['kepid','kepoi_name'])

# Fully duplicate rows (every column identical)
df.duplicated().sum()

# Duplicate kepoi_name alone (should really be unique — it's the KOI identifier)
df.duplicated(subset=['kepoi_name']).sum()

# Duplicate kepid alone (NOT expected to be unique — one star can host multiple planet candidates)
df.duplicated(subset=['kepid']).sum()

np.int64(1350)

In [37]:
#Which columns are essentially "ID" columns (won't be useful as features)?
# For each column, what fraction of values are unique?
df.nunique() / len(df)

unique = pd.DataFrame({
    'dtype': df.dtypes,
    'n_unique': df.nunique(),
    'pct_unique': (df.nunique() / len(df) * 100).round(1)
}).sort_values('pct_unique', ascending=False)
unique.iloc[0]

dtype         object
n_unique        9564
pct_unique     100.0
Name: kepoi_name, dtype: object

2. Target variable

What are the unique values of koi_disposition? What's the distribution (counts and percentages)?
How does koi_disposition relate to koi_pdisposition? Do they ever disagree?
What does koi_score look like for each disposition class? (try a groupby + describe, or boxplot)

In [42]:
#What are the unique values of koi_disposition? What's the distribution (counts and percentages)?
unique_koi_disposition = df.koi_disposition.nunique()
pct_unique_koi_disposition = (df.koi_disposition.nunique() / len(df) * 100)
unique_koi_disposition,pct_unique_koi_disposition

(3, 0.031367628607277286)

In [46]:
#How does koi_disposition relate to koi_pdisposition? Do they ever disagree?
pd.crosstab(df['koi_disposition'], df['koi_pdisposition'])

koi_pdisposition  CANDIDATE  FALSE POSITIVE
koi_disposition
CANDIDATE              2248               0
CONFIRMED              2248              45
FALSE POSITIVE            0            5023

In [51]:
#What does koi_score look like for each disposition class? (try a groupby + describe, or boxplot)
df.groupby("koi_disposition")["koi_score"].describe()

                  count      mean       std    min    25%    50%  75%    max
koi_disposition
CANDIDATE        1797.0  0.900210  0.182814  0.001  0.898  0.987  1.0  1.000
CONFIRMED        2281.0  0.962597  0.144498  0.000  0.993  1.000  1.0  1.000
FALSE POSITIVE   3976.0  0.014899  0.062409  0.000  0.000  0.000  0.0  0.957