# Reddit - Data is Beautiful

In [1]:
import pandas as pd

In [16]:
df = pd.read_csv(r"datasets/r_dataisbeautiful_posts.csv",low_memory=False)

Level 1 - Basic Pandas (loading, exploring, filtering)

Load the dataset and display shape, dtypes, and first 10 rows. How many posts exist?
How many posts have over_18 flagged as True?
Filter posts where score > 1000 and show the top 10 by score.
How many posts have missing values in each column? Which column has the most nulls?
Find all posts by a specific author (pick one from the data).

In [18]:
#Load the dataset and display shape, dtypes, and first 10 rows. How many posts exist?
print(f"The shape of the data set is {df.shape}")
print(f"The No. of posts that exist are {df.size}")
print(f"The dtypes int the data set are: \n {df.dtypes}")

The shape of the data set is (190853, 12)
The No. of posts that exist are 2290236
The dtypes int the data set are:
 id                        object
title                     object
score                      int64
author                    object
author_flair_text         object
removed_by                object
total_awards_received    float64
awarders                  object
created_utc                int64
full_link                 object
num_comments               int64
over_18                     bool
dtype: object

In [23]:
#How many posts have over_18 flagged as True?
count = df[df["over_18"] == True].size
print(f"{count} posts have over_18 flagged as True")

12816 posts have over_18 flagged as True

In [25]:
#Filter posts where score > 1000 and show the top 10 by score.
df[df["score"] > 1000].head(10)

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
460,lchi0x,[OC] Vegetation of Africa 2019,34837,Master4pprentice,OC: 7,NaN,38.0,[],1612450963,https://www.reddit.com/r/dataisbeautiful/comme...,441,False
508,lc8q1p,Number of Wilhelm Screams per Lord of the Ring...,29475,SvodeIsCool,OC: 2,NaN,31.0,[],1612417119,https://www.reddit.com/r/dataisbeautiful/comme...,685,False
534,lbtp5e,Robinhood is getting wrecked in the App Store ...,68617,chartr,OC: 82,NaN,93.0,[],1612375281,https://www.reddit.com/r/dataisbeautiful/comme...,2120,False
571,lbdfbp,[OC] Fails-To-Deliver data on GameStop (GME),13470,whereAreTheShares,OC: 2,NaN,24.0,[],1612319670,https://www.reddit.com/r/dataisbeautiful/comme...,1482,False
631,lau1dl,[OC] Unemployment Rate of The Baltic States si...,17473,shrek69_420,OC: 7,NaN,15.0,[],1612267393,https://www.reddit.com/r/dataisbeautiful/comme...,690,False
648,lahq0b,r/vocabwordoftheday went from 800 members to o...,3906,OverchargeRdt,NaN,moderator,4.0,[],1612222746,https://www.reddit.com/r/dataisbeautiful/comme...,306,False
659,laeb6v,"By popular demand, here is the ""boring version...",2418,delugetheory,OC: 4,NaN,5.0,[],1612213962,https://www.reddit.com/r/dataisbeautiful/comme...,309,False
765,l9gwrr,Orgasm frequency in partnered sex during the p...,4630,theimpossiblesalad,OC: 57,NaN,15.0,[],1612113732,https://www.reddit.com/r/dataisbeautiful/comme...,832,False
771,l9f4nu,Citadel paid $88 million to Robinhood in Q3 20...,46019,getToTheChopin,OC: 11,NaN,54.0,[],1612108856,https://www.reddit.com/r/dataisbeautiful/comme...,2971,False
772,l9f3a1,Urban Megaregions of the United States [OC],1294,delugetheory,OC: 4,NaN,3.0,[],1612108765,https://www.reddit.com/r/dataisbeautiful/comme...,277,False

In [29]:
#How many posts have missing values in each column? Which column has the most nulls?
missing = df.isnull().sum()
print(missing)

print(f"\nColumn with most nulls: {missing.idxmax()} ({missing.max()} missing values)")

id                            0
title                         1
score                         0
author                        0
author_flair_text        162008
removed_by               170109
total_awards_received    125707
awarders                 136375
created_utc                   0
full_link                     0
num_comments                  0
over_18                       0
dtype: int64

Column with most nulls: removed_by (170109 missing values)

In [31]:
#Find all posts by a specific author (pick one from the data).
df[df["author"] == "delugetheory"]

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
659,laeb6v,"By popular demand, here is the ""boring version...",2418,delugetheory,OC: 4,NaN,5.0,[],1612213962,https://www.reddit.com/r/dataisbeautiful/comme...,309,False
772,l9f3a1,Urban Megaregions of the United States [OC],1294,delugetheory,OC: 4,NaN,3.0,[],1612108765,https://www.reddit.com/r/dataisbeautiful/comme...,277,False
1083,l521tt,The World Divided into Three Regions of Equal ...,1,delugetheory,OC: 1,NaN,0.0,[],1611621761,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
1084,l520q2,The World Divided into Three Regions of Equal ...,1,delugetheory,OC: 1,moderator,0.0,[],1611621667,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
24186,greunh,Reddit Gold Awarded by U.S. Metropolitan Area ...,1,delugetheory,NaN,NaN,0.0,[],1590563423,https://www.reddit.com/r/dataisbeautiful/comme...,10,False
41958,f3fq22,America's Most and Least Average States [OC],1,delugetheory,NaN,NaN,0.0,[],1581623498,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
42006,f3axdt,America's Most and Least Average States [OC],1,delugetheory,NaN,NaN,0.0,[],1581604906,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
44480,eqgbsg,Metropolitan States of America: The 50 states ...,1,delugetheory,NaN,NaN,0.0,[],1579353798,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
44543,eq3696,Metropolitan States of America: The 50 states ...,1,delugetheory,NaN,NaN,0.0,[],1579280876,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
49817,e0ynfs,The West vs. The Rest: The World Divided Into ...,1,delugetheory,NaN,NaN,0.0,[],1574602931,https://www.reddit.com/r/dataisbeautiful/comme...,2199,False
50425,dxab2h,Quality of Life in the United States (as measu...,1,delugetheory,NaN,NaN,0.0,[],1573927750,https://www.reddit.com/r/dataisbeautiful/comme...,47,False
61996,bv9pjm,Ethnic Composition of the United States [OC],4,delugetheory,NaN,NaN,0.0,NaN,1559320228,https://www.reddit.com/r/dataisbeautiful/comme...,4,False
62296,btphvv,Hipster Map of the United States (interactive ...,2,delugetheory,NaN,NaN,0.0,NaN,1558981855,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
62299,btpdjd,Hipster Map of the United States [OC],1,delugetheory,NaN,NaN,0.0,NaN,1558981274,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
66376,bbaqiv,I overlaid the most popular US cultural region...,2,delugetheory,NaN,NaN,NaN,NaN,1554830844,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
77976,9v9ird,How Tuesday's U.S. Midterm Election Might Have...,1,delugetheory,OC: 2,NaN,NaN,NaN,1541679696,https://www.reddit.com/r/dataisbeautiful/comme...,25,False
80443,9je1iz,2016 U.S. Presidential Election Results ...if ...,5767,delugetheory,OC: 2,NaN,NaN,NaN,1538063552,https://www.reddit.com/r/dataisbeautiful/comme...,1017,False
80444,9je1dr,2016 U.S. Presidential Election Results ...if ...,2014,delugetheory,OC: 2,NaN,NaN,NaN,1538063531,https://www.reddit.com/r/dataisbeautiful/comme...,439,False
80841,9hieae,Most Historically Popular Presidential Candida...,40,delugetheory,OC: 1,NaN,NaN,NaN,1537473209,https://www.reddit.com/r/dataisbeautiful/comme...,13,False
80842,9hibzi,Most Historically *Unpopular* Presidential Can...,272,delugetheory,OC: 1,NaN,NaN,NaN,1537472779,https://www.reddit.com/r/dataisbeautiful/comme...,36,False
80851,9hgw7b,Most Historically Popular Presidential Candida...,48,delugetheory,NaN,NaN,NaN,NaN,1537462273,https://www.reddit.com/r/dataisbeautiful/comme...,14,False
83540,95nc7v,6 Percentage of Total National Population Belo...,9,delugetheory,OC: 3,NaN,NaN,NaN,1533744319,https://www.reddit.com/r/dataisbeautiful/comme...,3,False
83545,95n3u4,Percentage of Total National Population Belong...,6,delugetheory,OC: 3,NaN,NaN,NaN,1533742795,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
89697,8ie504,Hypothetical U.S. Presidential Candidate Face-...,24,delugetheory,NaN,NaN,NaN,NaN,1525951509,https://www.reddit.com/r/dataisbeautiful/comme...,9,False
90128,8gq6gr,"Where Do ""Red America"" and ""Blue America"" Live...",53,delugetheory,NaN,NaN,NaN,NaN,1525352439,https://www.reddit.com/r/dataisbeautiful/comme...,19,False
90137,8gpm6i,"Where Do ""Red America"" and ""Blue America"" Live...",2,delugetheory,NaN,NaN,NaN,NaN,1525346524,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
90617,8f1rk7,United States of Apathy: 2016 US Presidential ...,60955,delugetheory,OC: 3,NaN,NaN,NaN,1524740540,https://www.reddit.com/r/dataisbeautiful/comme...,7073,False
90998,8dq6p2,Apathetic States of America - 2016 US Election...,3,delugetheory,OC: 1,NaN,NaN,NaN,1524251607,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
91025,8dnmhv,American Mosaic: Largest Racial/Ethnic Group a...,14462,delugetheory,OC: 1,NaN,NaN,NaN,1524231455,https://www.reddit.com/r/dataisbeautiful/comme...,1342,False
91141,8d6o8k,"Quality of Life in the United States, Based on...",386,delugetheory,OC: 1,NaN,NaN,NaN,1524066661,https://www.reddit.com/r/dataisbeautiful/comme...,73,False
93829,8384h8,"Urban Areas (Population 1,000,000+) that Are t...",33,delugetheory,OC: 1,NaN,NaN,NaN,1520614257,https://www.reddit.com/r/dataisbeautiful/comme...,6,False
168245,2n1nhc,"'Where We Came From and Where We Went, State b...",6,delugetheory,NaN,NaN,NaN,NaN,1416622247,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
179610,24nudg,'Blue Dots in Red States and Red Dots in Blue ...,118,delugetheory,NaN,NaN,NaN,NaN,1399165754,https://www.reddit.com/r/dataisbeautiful/comme...,37,False
183739,1q3003,"Worldwide Map of Regional Subreddits with 10,0...",20,delugetheory,NaN,NaN,NaN,NaN,1383802210,https://www.reddit.com/r/dataisbeautiful/comme...,4,False
186019,1hvydl,'The United States of Reddit': A Voronoi Diagr...,184,delugetheory,NaN,NaN,NaN,NaN,1373315441,https://www.reddit.com/r/dataisbeautiful/comme...,69,False
186267,1gy3u8,I blended the colors of each country's flag in...,285,delugetheory,NaN,NaN,NaN,NaN,1372044733,https://www.reddit.com/r/dataisbeautiful/comme...,31,False
186320,1gnna6,'Lingua Francas' - Seven Languages Which Cumul...,880,delugetheory,NaN,NaN,NaN,NaN,1371652202,https://www.reddit.com/r/dataisbeautiful/comme...,258,False
187726,1azgwr,The Current State of Personal Liberties in the...,93,delugetheory,NaN,NaN,NaN,NaN,1364233494,https://www.reddit.com/r/dataisbeautiful/comme...,65,False
188817,161n8s,Congressional Representation in the United Sta...,32,delugetheory,NaN,NaN,NaN,NaN,1357447400,https://www.reddit.com/r/dataisbeautiful/comme...,10,False
189187,13urhj,"Cities of Reddit: Local US Subreddits with 5,0...",100,delugetheory,NaN,NaN,NaN,NaN,1353988102,https://www.reddit.com/r/dataisbeautiful/comme...,35,False