# Reddit - Data is Beautiful

In [1]:
import pandas as pd

In [63]:
df = pd.read_csv(r"datasets/r_dataisbeautiful_posts.csv",low_memory=False)
df.head()

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
0,ll1p9h,Wordcloud of trending video titles on YouTube ...,1,OmarZiada,OC: 1,NaN,0.0,[],1613473961,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
1,ll1o4h,Wordcloud of trending videos on YouTube in the...,1,OmarZiada,OC: 1,moderator,0.0,[],1613473829,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
2,ll15gx,Immunization in India. Source: https://niti.go...,1,Professional_Napper_,NaN,moderator,0.0,[],1613471541,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
3,ll0iup,How to quickly estimate the impact of players ...,1,Viziball,NaN,automod_filtered,0.0,[],1613468624,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
4,ll0g9a,How to quickly estimate the impact of players ...,1,Viziball,NaN,moderator,0.0,[],1613468281,https://www.reddit.com/r/dataisbeautiful/comme...,2,False

Level 1 - Basic Pandas (loading, exploring, filtering)

Load the dataset and display shape, dtypes, and first 10 rows. How many posts exist?
How many posts have over_18 flagged as True?
Filter posts where score > 1000 and show the top 10 by score.
How many posts have missing values in each column? Which column has the most nulls?
Find all posts by a specific author (pick one from the data).

In [18]:
#Load the dataset and display shape, dtypes, and first 10 rows. How many posts exist?
print(f"The shape of the data set is {df.shape}")
print(f"The No. of posts that exist are {df.size}")
print(f"The dtypes int the data set are: \n {df.dtypes}")

The shape of the data set is (190853, 12)
The No. of posts that exist are 2290236
The dtypes int the data set are:
 id                        object
title                     object
score                      int64
author                    object
author_flair_text         object
removed_by                object
total_awards_received    float64
awarders                  object
created_utc                int64
full_link                 object
num_comments               int64
over_18                     bool
dtype: object

In [23]:
#How many posts have over_18 flagged as True?
count = df[df["over_18"] == True].size
print(f"{count} posts have over_18 flagged as True")

12816 posts have over_18 flagged as True

In [25]:
#Filter posts where score > 1000 and show the top 10 by score.
df[df["score"] > 1000].head(10)

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
460,lchi0x,[OC] Vegetation of Africa 2019,34837,Master4pprentice,OC: 7,NaN,38.0,[],1612450963,https://www.reddit.com/r/dataisbeautiful/comme...,441,False
508,lc8q1p,Number of Wilhelm Screams per Lord of the Ring...,29475,SvodeIsCool,OC: 2,NaN,31.0,[],1612417119,https://www.reddit.com/r/dataisbeautiful/comme...,685,False
534,lbtp5e,Robinhood is getting wrecked in the App Store ...,68617,chartr,OC: 82,NaN,93.0,[],1612375281,https://www.reddit.com/r/dataisbeautiful/comme...,2120,False
571,lbdfbp,[OC] Fails-To-Deliver data on GameStop (GME),13470,whereAreTheShares,OC: 2,NaN,24.0,[],1612319670,https://www.reddit.com/r/dataisbeautiful/comme...,1482,False
631,lau1dl,[OC] Unemployment Rate of The Baltic States si...,17473,shrek69_420,OC: 7,NaN,15.0,[],1612267393,https://www.reddit.com/r/dataisbeautiful/comme...,690,False
648,lahq0b,r/vocabwordoftheday went from 800 members to o...,3906,OverchargeRdt,NaN,moderator,4.0,[],1612222746,https://www.reddit.com/r/dataisbeautiful/comme...,306,False
659,laeb6v,"By popular demand, here is the ""boring version...",2418,delugetheory,OC: 4,NaN,5.0,[],1612213962,https://www.reddit.com/r/dataisbeautiful/comme...,309,False
765,l9gwrr,Orgasm frequency in partnered sex during the p...,4630,theimpossiblesalad,OC: 57,NaN,15.0,[],1612113732,https://www.reddit.com/r/dataisbeautiful/comme...,832,False
771,l9f4nu,Citadel paid $88 million to Robinhood in Q3 20...,46019,getToTheChopin,OC: 11,NaN,54.0,[],1612108856,https://www.reddit.com/r/dataisbeautiful/comme...,2971,False
772,l9f3a1,Urban Megaregions of the United States [OC],1294,delugetheory,OC: 4,NaN,3.0,[],1612108765,https://www.reddit.com/r/dataisbeautiful/comme...,277,False

In [29]:
#How many posts have missing values in each column? Which column has the most nulls?
missing = df.isnull().sum()
print(missing)

print(f"\nColumn with most nulls: {missing.idxmax()} ({missing.max()} missing values)")

id                            0
title                         1
score                         0
author                        0
author_flair_text        162008
removed_by               170109
total_awards_received    125707
awarders                 136375
created_utc                   0
full_link                     0
num_comments                  0
over_18                       0
dtype: int64

Column with most nulls: removed_by (170109 missing values)

In [31]:
#Find all posts by a specific author (pick one from the data).
df[df["author"] == "delugetheory"]

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
659,laeb6v,"By popular demand, here is the ""boring version...",2418,delugetheory,OC: 4,NaN,5.0,[],1612213962,https://www.reddit.com/r/dataisbeautiful/comme...,309,False
772,l9f3a1,Urban Megaregions of the United States [OC],1294,delugetheory,OC: 4,NaN,3.0,[],1612108765,https://www.reddit.com/r/dataisbeautiful/comme...,277,False
1083,l521tt,The World Divided into Three Regions of Equal ...,1,delugetheory,OC: 1,NaN,0.0,[],1611621761,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
1084,l520q2,The World Divided into Three Regions of Equal ...,1,delugetheory,OC: 1,moderator,0.0,[],1611621667,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
24186,greunh,Reddit Gold Awarded by U.S. Metropolitan Area ...,1,delugetheory,NaN,NaN,0.0,[],1590563423,https://www.reddit.com/r/dataisbeautiful/comme...,10,False
41958,f3fq22,America's Most and Least Average States [OC],1,delugetheory,NaN,NaN,0.0,[],1581623498,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
42006,f3axdt,America's Most and Least Average States [OC],1,delugetheory,NaN,NaN,0.0,[],1581604906,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
44480,eqgbsg,Metropolitan States of America: The 50 states ...,1,delugetheory,NaN,NaN,0.0,[],1579353798,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
44543,eq3696,Metropolitan States of America: The 50 states ...,1,delugetheory,NaN,NaN,0.0,[],1579280876,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
49817,e0ynfs,The West vs. The Rest: The World Divided Into ...,1,delugetheory,NaN,NaN,0.0,[],1574602931,https://www.reddit.com/r/dataisbeautiful/comme...,2199,False
50425,dxab2h,Quality of Life in the United States (as measu...,1,delugetheory,NaN,NaN,0.0,[],1573927750,https://www.reddit.com/r/dataisbeautiful/comme...,47,False
61996,bv9pjm,Ethnic Composition of the United States [OC],4,delugetheory,NaN,NaN,0.0,NaN,1559320228,https://www.reddit.com/r/dataisbeautiful/comme...,4,False
62296,btphvv,Hipster Map of the United States (interactive ...,2,delugetheory,NaN,NaN,0.0,NaN,1558981855,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
62299,btpdjd,Hipster Map of the United States [OC],1,delugetheory,NaN,NaN,0.0,NaN,1558981274,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
66376,bbaqiv,I overlaid the most popular US cultural region...,2,delugetheory,NaN,NaN,NaN,NaN,1554830844,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
77976,9v9ird,How Tuesday's U.S. Midterm Election Might Have...,1,delugetheory,OC: 2,NaN,NaN,NaN,1541679696,https://www.reddit.com/r/dataisbeautiful/comme...,25,False
80443,9je1iz,2016 U.S. Presidential Election Results ...if ...,5767,delugetheory,OC: 2,NaN,NaN,NaN,1538063552,https://www.reddit.com/r/dataisbeautiful/comme...,1017,False
80444,9je1dr,2016 U.S. Presidential Election Results ...if ...,2014,delugetheory,OC: 2,NaN,NaN,NaN,1538063531,https://www.reddit.com/r/dataisbeautiful/comme...,439,False
80841,9hieae,Most Historically Popular Presidential Candida...,40,delugetheory,OC: 1,NaN,NaN,NaN,1537473209,https://www.reddit.com/r/dataisbeautiful/comme...,13,False
80842,9hibzi,Most Historically *Unpopular* Presidential Can...,272,delugetheory,OC: 1,NaN,NaN,NaN,1537472779,https://www.reddit.com/r/dataisbeautiful/comme...,36,False
80851,9hgw7b,Most Historically Popular Presidential Candida...,48,delugetheory,NaN,NaN,NaN,NaN,1537462273,https://www.reddit.com/r/dataisbeautiful/comme...,14,False
83540,95nc7v,6 Percentage of Total National Population Belo...,9,delugetheory,OC: 3,NaN,NaN,NaN,1533744319,https://www.reddit.com/r/dataisbeautiful/comme...,3,False
83545,95n3u4,Percentage of Total National Population Belong...,6,delugetheory,OC: 3,NaN,NaN,NaN,1533742795,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
89697,8ie504,Hypothetical U.S. Presidential Candidate Face-...,24,delugetheory,NaN,NaN,NaN,NaN,1525951509,https://www.reddit.com/r/dataisbeautiful/comme...,9,False
90128,8gq6gr,"Where Do ""Red America"" and ""Blue America"" Live...",53,delugetheory,NaN,NaN,NaN,NaN,1525352439,https://www.reddit.com/r/dataisbeautiful/comme...,19,False
90137,8gpm6i,"Where Do ""Red America"" and ""Blue America"" Live...",2,delugetheory,NaN,NaN,NaN,NaN,1525346524,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
90617,8f1rk7,United States of Apathy: 2016 US Presidential ...,60955,delugetheory,OC: 3,NaN,NaN,NaN,1524740540,https://www.reddit.com/r/dataisbeautiful/comme...,7073,False
90998,8dq6p2,Apathetic States of America - 2016 US Election...,3,delugetheory,OC: 1,NaN,NaN,NaN,1524251607,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
91025,8dnmhv,American Mosaic: Largest Racial/Ethnic Group a...,14462,delugetheory,OC: 1,NaN,NaN,NaN,1524231455,https://www.reddit.com/r/dataisbeautiful/comme...,1342,False
91141,8d6o8k,"Quality of Life in the United States, Based on...",386,delugetheory,OC: 1,NaN,NaN,NaN,1524066661,https://www.reddit.com/r/dataisbeautiful/comme...,73,False
93829,8384h8,"Urban Areas (Population 1,000,000+) that Are t...",33,delugetheory,OC: 1,NaN,NaN,NaN,1520614257,https://www.reddit.com/r/dataisbeautiful/comme...,6,False
168245,2n1nhc,"'Where We Came From and Where We Went, State b...",6,delugetheory,NaN,NaN,NaN,NaN,1416622247,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
179610,24nudg,'Blue Dots in Red States and Red Dots in Blue ...,118,delugetheory,NaN,NaN,NaN,NaN,1399165754,https://www.reddit.com/r/dataisbeautiful/comme...,37,False
183739,1q3003,"Worldwide Map of Regional Subreddits with 10,0...",20,delugetheory,NaN,NaN,NaN,NaN,1383802210,https://www.reddit.com/r/dataisbeautiful/comme...,4,False
186019,1hvydl,'The United States of Reddit': A Voronoi Diagr...,184,delugetheory,NaN,NaN,NaN,NaN,1373315441,https://www.reddit.com/r/dataisbeautiful/comme...,69,False
186267,1gy3u8,I blended the colors of each country's flag in...,285,delugetheory,NaN,NaN,NaN,NaN,1372044733,https://www.reddit.com/r/dataisbeautiful/comme...,31,False
186320,1gnna6,'Lingua Francas' - Seven Languages Which Cumul...,880,delugetheory,NaN,NaN,NaN,NaN,1371652202,https://www.reddit.com/r/dataisbeautiful/comme...,258,False
187726,1azgwr,The Current State of Personal Liberties in the...,93,delugetheory,NaN,NaN,NaN,NaN,1364233494,https://www.reddit.com/r/dataisbeautiful/comme...,65,False
188817,161n8s,Congressional Representation in the United Sta...,32,delugetheory,NaN,NaN,NaN,NaN,1357447400,https://www.reddit.com/r/dataisbeautiful/comme...,10,False
189187,13urhj,"Cities of Reddit: Local US Subreddits with 5,0...",100,delugetheory,NaN,NaN,NaN,NaN,1353988102,https://www.reddit.com/r/dataisbeautiful/comme...,35,False

Level 2 - Aggregation & Grouping

Who are the top 10 most active authors by post count?
What is the average score per removed_by category? (moderator vs reddit vs automod vs none)
Which author_flair_text label gets the highest average score?
How many posts were removed by each removal type? What % of total posts does each represent?
Find authors who have posted more than 5 times and their average score.

In [33]:
#Who are the top 10 most active authors by post count?
top_authors = df["author"].value_counts().head(10)
print(top_authors)

author
[deleted]     26849
jimrosenz      1744
OverflowDs      446
caobanlong      314
pdwp90          300
neilrkaye       284
BoMcCready      280
rhiever         272
RAGTIMEMA       266
sofl96          262
Name: count, dtype: int64

In [40]:
#What is the average score per removed_by category? (moderator vs reddit vs automod vs none)
average_score_by_removed_by = (
    df[df["removed_by"].isin(['moderator', 'reddit', 'automod', 'none'])]
    .groupby("removed_by")["score"]
    .mean()
)
print(average_score_by_removed_by)

removed_by
moderator    8.939955
reddit       1.004818
Name: score, dtype: float64

In [47]:
#Which author_flair_text label gets the highest average score?
average_score_by_author_flair_text = (
    df.groupby("author_flair_text")["score"].mean())
print(df.groupby("author_flair_text")["score"].mean().idxmax())

OC: 137

In [51]:
#How many posts were removed by each removal type? What % of total posts does each represent?
removal_counts = df["removed_by"].value_counts()
removal_pct = df["removed_by"].value_counts(normalize=True) * 100

removal_summary = pd.DataFrame({
    "count": removal_counts,
    "percentage": removal_pct.round(2)
})

print(removal_summary)

                  count  percentage
removed_by
moderator         14789       71.29
deleted            2948       14.21
automod_filtered   1553        7.49
reddit             1453        7.00
author                1        0.00

In [59]:
# Find authors who have posted more than 5 times and their average score.
author_counts = df["author"].value_counts()
active_authors = author_counts[author_counts > 5]

author_avg_score = df[df["author"].isin(active_authors.index)].groupby("author")["score"].mean()

result = pd.DataFrame({
    "post_count": active_authors,
    "avg_score": author_avg_score
}).sort_values("avg_score", ascending=False)

print(result)

                 post_count     avg_score
author
citrusvanilla             6  17489.333333
sandusky_hohoho          13  14524.615385
Tjukanov                 11  14141.363636
DR-ROBERT-J               6  10805.333333
madewulf                  7  10412.714286
...                     ...           ...
crazyby                   9      0.222222
foooga                    6      0.166667
antoniokburt              7      0.142857
arenafox22                8      0.125000
EllieRoe2255              8      0.000000

[3152 rows x 2 columns]

Level 3 - String & Date Operations

Convert created_utc (Unix timestamp) to a readable datetime column. What date range does the dataset cover?
What hour of the day sees the most posts? (extract hour from datetime)
What % of posts have [OC] in the title? Do OC posts score higher on average?
Find all posts mentioning "COVID" or "covid" in the title.
Extract the subreddit name from full_link using string methods.

In [70]:
#Convert created_utc (Unix timestamp) to a readable datetime column. What date range does the dataset cover?
df["created_dt"] = pd.to_datetime(df["created_utc"], unit="s")
print(f"Start date : {df['created_dt'].min()}")
print(f"End date   : {df['created_dt'].max()}")
print(f"Date range : {df['created_dt'].max() - df['created_dt'].min()}")

Start date : 2012-02-14 23:50:56
End date   : 2021-02-16 11:12:41
Date range : 3289 days 11:21:45

In [73]:
#What hour of the day sees the most posts? (extract hour from datetime)
hours = df["created_dt"].dt.hour
print(f"Peak hour: {hours.value_counts().idxmax()}:00")
print(hours.value_counts().sort_index())  # full breakdown by hour

Peak hour: 15:00
created_dt
0      6563
1      6548
2      6394
3      6120
4      5650
5      5392
6      5250
7      5323
8      5265
9      5721
10     6071
11     7020
12     8623
13    10233
14    11119
15    11703
16    11461
17    11105
18    10751
19    10389
20     9758
21     9067
22     8049
23     7278
Name: count, dtype: int64

In [74]:
#What % of posts have [OC] in the title? Do OC posts score higher on average?
df["is_oc"] = df["title"].str.contains(r"\[OC\]", case=False, na=False)

oc_pct = df["is_oc"].mean() * 100
print(f"OC posts: {oc_pct:.2f}%")

print(df.groupby("is_oc")["score"].mean())

OC posts: 34.97%
is_oc
False     58.060858
True     395.351447
Name: score, dtype: float64

In [75]:
#Find all posts mentioning "COVID" or "covid" in the title.
covid_posts = df[df["title"].str.contains("covid", case=False, na=False)]
print(f"Total COVID posts: {len(covid_posts)}")
print(covid_posts["title"].head(10))

Total COVID posts: 7049
17     Timeline of U.S. COVID-19 Cases over Time (Mar...
37     [OC] The way my first COVID shot (on a Saturda...
72     Can anyone guess the date I received a positiv...
112    Top 15 Covid19 Vaccinated Countries | Timelaps...
140    [OC] THE SUM of cases that are infected with t...
164    Covid-19 vaccines are great — here’s why you a...
218    [OC] US States Covid Case Rate Change / Contai...
220    [OC] Would you get the COVID-19 vaccine tomorr...
266    Trump Twitter ban coincides with steep decline...
276    The Resiliency of Healthcare Workers During CO...
Name: title, dtype: object

In [76]:
df["subreddit_extracted"] = df["full_link"].str.split("/").str[4]
print(df[["full_link", "subreddit_extracted"]].head())

                                           full_link subreddit_extracted
0  https://www.reddit.com/r/dataisbeautiful/comme...     dataisbeautiful
1  https://www.reddit.com/r/dataisbeautiful/comme...     dataisbeautiful
2  https://www.reddit.com/r/dataisbeautiful/comme...     dataisbeautiful
3  https://www.reddit.com/r/dataisbeautiful/comme...     dataisbeautiful
4  https://www.reddit.com/r/dataisbeautiful/comme...     dataisbeautiful

In [42]:
df.columns

Index(['id', 'title', 'score', 'author', 'author_flair_text', 'removed_by',
       'total_awards_received', 'awarders', 'created_utc', 'full_link',
       'num_comments', 'over_18'],
      dtype='object')