In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r'/Users/mukundanramesh/projects/ai_ml_course_bootcamp_practice/ai-ml-course-bootcamp/Pandas/datasets/global_ev_adoption_behavior_2026.csv')
df.head()

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,environmental_awareness_score,government_incentive_awareness,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost
0,56,23019.0,High School,Suburban,39.8,205.7,Hatchback,6.1,317.1,3.9,...,8.3,6.4,5.2,4.6,3.5,6.9,0,High,199.8,28.5
1,46,26440.0,High School,Suburban,34.6,218.4,Sedan,4.4,290.0,4.5,...,7.8,10.0,5.7,5.5,7.4,6.9,1,High,139.8,22.9
2,46,57167.0,PhD,Suburban,30.5,177.7,Sedan,0.4,201.4,6.3,...,7.6,6.4,7.8,5.3,6.2,6.8,0,High,158.0,38.5
3,23,15841.0,Master,Suburban,44.6,325.9,SUV,0.0,407.3,5.2,...,6.2,5.6,5.1,7.9,5.7,7.2,0,Low,207.0,45.0
4,50,51571.0,Master,Urban,52.4,281.0,SUV,5.2,458.4,4.3,...,9.7,9.9,8.2,2.6,4.7,8.1,0,High,195.6,43.9

In [7]:
#Load the CSV and print its shape (rows/columns) and column names.
print(f"The shape of the data set is {df.shape}")
print(f"The columns available in the data set are \n {df.columns}")

The shape of the data set is (50000, 23)
The columns available in the data set are
 Index(['age', 'annual_income', 'education_level', 'city_type',
       'daily_commute_km', 'weekly_travel_distance_km', 'current_vehicle_type',
       'vehicle_age_years', 'fuel_expense_per_month',
       'charging_station_accessibility', 'nearest_charging_station_km',
       'home_charging_available', 'electricity_cost_per_kwh',
       'environmental_awareness_score', 'government_incentive_awareness',
       'technology_affinity_score', 'range_anxiety_score',
       'battery_replacement_concern', 'ev_knowledge_score',
       'previous_ev_experience', 'ev_adoption_likelihood',
       'monthly_energy_consumption_kwh', 'monthly_charging_cost'],
      dtype='object')

In [10]:
#Check data types of each column — which are numeric vs. categorical?
df.dtypes

age                                 int64
annual_income                     float64
education_level                    object
city_type                          object
daily_commute_km                  float64
weekly_travel_distance_km         float64
current_vehicle_type               object
vehicle_age_years                 float64
fuel_expense_per_month            float64
charging_station_accessibility    float64
nearest_charging_station_km       float64
home_charging_available             int64
electricity_cost_per_kwh          float64
environmental_awareness_score     float64
government_incentive_awareness    float64
technology_affinity_score         float64
range_anxiety_score               float64
battery_replacement_concern       float64
ev_knowledge_score                float64
previous_ev_experience              int64
ev_adoption_likelihood             object
monthly_energy_consumption_kwh    float64
monthly_charging_cost             float64
dtype: object

In [16]:
# Find missing values in each column. Which 3 columns have missing data, and how many rows are affected?
df.isna().sum().sort_values(ascending = False)[:3]

education_level                   500
ev_knowledge_score                500
charging_station_accessibility    500
dtype: int64

In [19]:
#4. What is the average age, annual income, and daily commute distance of people in this dataset?
columns = ['age','annual_income','daily_commute_km']
df[columns].mean()

age                    44.996080
annual_income       44311.869380
daily_commute_km       35.169358
dtype: float64

In [20]:
#5. What is the minimum, maximum, and median monthly_charging_cost?
monthly_charging_cost = df.monthly_charging_cost
print(f"The minimum chargin cost is {monthly_charging_cost.min()}, the maximum charging cost is {monthly_charging_cost.max()} and the median charging cose is {monthly_charging_cost.median()}")

The minimum chargin cost is 1.4, the maximum charging cost is 199.6 and the average charging cose is 35.2

In [28]:
#6. What percentage of people already have home_charging_available?
pct_home_charging_available = ((df.home_charging_available == True).sum() / len(df)) *100
print(f"{pct_home_charging_available:.2f}% of people have home_charging_available")

64.98% of people have home_charging_available

In [29]:
#7. What percentage of people have previous_ev_experience?
pct_previous_ev_experience = ((df.previous_ev_experience == True).sum() / len(df)) *100
print(f"{pct_previous_ev_experience:.2f}% of people have previous_ev_experience")

19.82% of people have previous_ev_experience

In [39]:
#8. How many people fall into each ev_adoption_likelihood category (High/Medium/Low)? Show as counts and percentages.
df.groupby('ev_adoption_likelihood')['ev_adoption_likelihood'].count()

ev_adoption_likelihood
High      29670
Low        8252
Medium    12078
Name: ev_adoption_likelihood, dtype: int64

In [40]:
#9. What is the distribution of city_type (Urban/Suburban/Rural)? Which is most common?
df.groupby('city_type')['city_type'].count()

city_type
Rural       10007
Suburban    17348
Urban       22645
Name: city_type, dtype: int64

In [41]:
#10. What is the distribution of current_vehicle_type (Hatchback/Sedan/SUV/Truck)?
df.groupby('current_vehicle_type')['current_vehicle_type'].count()

current_vehicle_type
Hatchback    12561
SUV          14933
Sedan        17512
Truck         4994
Name: current_vehicle_type, dtype: int64

In [46]:
#11 . How many people have each education_level?
df.groupby('education_level')['education_level'].count()

education_level
Bachelor       22350
High School    12401
Master         12244
PhD             2505
Name: education_level, dtype: int64

In [48]:
#12. What is the average annual_income for each ev_adoption_likelihood group (High vs Medium vs Low)?
df.groupby('ev_adoption_likelihood')['annual_income'].mean()

ev_adoption_likelihood
High      52219.834007
Low       29402.017693
Medium    35072.490810
Name: annual_income, dtype: float64

In [50]:
# 13. Does city_type affect average ev_adoption_likelihood-by-income? (i.e., group by city_type and compute average incom
df.groupby('city_type')['annual_income'].mean().sort_values(ascending=False)

city_type
Urban       44472.659086
Suburban    44266.227231
Rural       44027.140402
Name: annual_income, dtype: float64

In [52]:
#14. Compare the average range_anxiety_score and environmental_awareness_score between people who have previous_ev_experience and those who don't.
df.groupby('previous_ev_experience')[['range_anxiety_score','environmental_awareness_score']].mean()

                        range_anxiety_score  environmental_awareness_score
previous_ev_experience
0                                  5.289611                       6.836638
1                                  5.281715                       6.812503

In [56]:
#15. Is there a difference in nearest_charging_station_km between Urban, Suburban, and Rural areas?
df.groupby('city_type')['nearest_charging_station_km'].mean().sort_values(ascending=False)

city_type
Suburban    10.032056
Rural        9.988078
Urban        3.649004
Name: nearest_charging_station_km, dtype: float64