In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'/Users/mukundanramesh/projects/ai_ml_course_bootcamp_practice/ai-ml-course-bootcamp/Pandas/datasets/global_ev_adoption_behavior_2026.csv')
df.head()

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,environmental_awareness_score,government_incentive_awareness,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost
0,56,23019.0,High School,Suburban,39.8,205.7,Hatchback,6.1,317.1,3.9,...,8.3,6.4,5.2,4.6,3.5,6.9,0,High,199.8,28.5
1,46,26440.0,High School,Suburban,34.6,218.4,Sedan,4.4,290.0,4.5,...,7.8,10.0,5.7,5.5,7.4,6.9,1,High,139.8,22.9
2,46,57167.0,PhD,Suburban,30.5,177.7,Sedan,0.4,201.4,6.3,...,7.6,6.4,7.8,5.3,6.2,6.8,0,High,158.0,38.5
3,23,15841.0,Master,Suburban,44.6,325.9,SUV,0.0,407.3,5.2,...,6.2,5.6,5.1,7.9,5.7,7.2,0,Low,207.0,45.0
4,50,51571.0,Master,Urban,52.4,281.0,SUV,5.2,458.4,4.3,...,9.7,9.9,8.2,2.6,4.7,8.1,0,High,195.6,43.9

In [3]:
#Use .loc[] to select rows 10–15 (inclusive) and only the columns age, annual_income, city_type.
df.loc[10:15]

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,environmental_awareness_score,government_incentive_awareness,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost
10,46,67343.0,Master,Suburban,18.8,133.6,SUV,8.7,133.7,5.6,...,6.4,8.9,8.5,3.2,5.0,8.8,0,High,131.6,28.7
11,42,27271.0,Bachelor,Urban,31.4,160.8,Hatchback,3.3,250.8,10.0,...,9.2,10.0,5.1,3.4,8.7,8.5,1,High,132.5,32.9
12,43,28828.0,Bachelor,Suburban,47.8,247.3,Truck,1.4,387.7,5.4,...,8.9,9.3,5.3,2.1,4.1,7.2,0,High,161.6,41.6
13,30,56928.0,Master,Rural,44.0,254.4,Sedan,6.0,399.8,8.9,...,8.7,8.3,6.9,3.9,6.1,8.5,0,High,241.9,81.0
14,32,86553.0,High School,Urban,41.7,220.3,Hatchback,5.4,330.6,5.8,...,7.6,7.8,8.4,3.1,5.6,8.8,0,High,149.5,40.1
15,57,20054.0,High School,Suburban,16.7,120.5,Sedan,7.9,50.0,1.0,...,8.1,5.2,8.7,5.7,7.0,8.5,0,Medium,98.1,10.5

In [5]:
#Use .iloc[] to select the first 5 rows and the first 3 columns.
df.iloc[:5,:3]

   age  annual_income education_level
0   56        23019.0     High School
1   46        26440.0     High School
2   46        57167.0             PhD
3   23        15841.0          Master
4   50        51571.0          Master

In [7]:
#Use .loc[] with .between() to select all rows where age is between 25 and 35.
df.loc[df.age.between(25,35)]

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,environmental_awareness_score,government_incentive_awareness,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost
13,30,56928.0,Master,Rural,44.0,254.4,Sedan,6.0,399.8,8.9,...,8.7,8.3,6.9,3.9,6.1,8.5,0,High,241.9,81.0
14,32,86553.0,High School,Urban,41.7,220.3,Hatchback,5.4,330.6,5.8,...,7.6,7.8,8.4,3.1,5.6,8.8,0,High,149.5,40.1
20,26,46292.0,Bachelor,Suburban,53.6,388.3,Truck,10.8,474.0,3.7,...,6.7,4.3,8.5,2.2,3.1,7.9,0,High,241.6,32.7
24,34,43948.0,Bachelor,Urban,23.4,149.3,Hatchback,7.7,208.8,10.0,...,10.0,2.8,7.1,4.8,5.4,7.8,0,High,110.5,22.2
33,33,43493.0,Bachelor,Urban,32.5,240.7,Sedan,12.8,250.3,9.2,...,10.0,6.5,8.5,4.4,8.6,NaN,0,High,224.1,35.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49987,29,20464.0,Master,Urban,7.4,48.1,Sedan,6.2,71.4,6.2,...,8.6,6.5,8.7,2.6,6.1,7.7,0,High,48.9,8.9
49993,27,92400.0,Bachelor,Suburban,16.6,127.8,Sedan,4.6,125.9,2.4,...,7.1,7.2,9.7,5.0,7.1,6.4,1,High,127.5,20.4
49994,29,80965.0,High School,Rural,39.7,238.4,SUV,9.1,285.9,7.2,...,9.9,9.5,9.0,5.5,6.8,8.6,0,High,179.5,33.3
49995,27,26296.0,Bachelor,Urban,37.4,211.4,Sedan,0.0,314.8,10.0,...,9.9,6.6,8.9,5.1,7.8,9.3,1,High,162.5,37.5
49997,30,20862.0,Master,Suburban,37.5,295.2,Sedan,0.0,358.4,7.7,...,7.3,6.6,4.5,5.2,1.3,5.9,0,High,218.3,52.8

In [11]:
#4. Check whether there are any fully duplicated rows using .duplicated().
df=pd.concat((df,df.copy()),axis=0)
df[df.duplicated()]

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,environmental_awareness_score,government_incentive_awareness,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost
0,56,23019.0,High School,Suburban,39.8,205.7,Hatchback,6.1,317.1,3.9,...,8.3,6.4,5.2,4.6,3.5,6.9,0,High,199.8,28.5
1,46,26440.0,High School,Suburban,34.6,218.4,Sedan,4.4,290.0,4.5,...,7.8,10.0,5.7,5.5,7.4,6.9,1,High,139.8,22.9
2,46,57167.0,PhD,Suburban,30.5,177.7,Sedan,0.4,201.4,6.3,...,7.6,6.4,7.8,5.3,6.2,6.8,0,High,158.0,38.5
3,23,15841.0,Master,Suburban,44.6,325.9,SUV,0.0,407.3,5.2,...,6.2,5.6,5.1,7.9,5.7,7.2,0,Low,207.0,45.0
4,50,51571.0,Master,Urban,52.4,281.0,SUV,5.2,458.4,4.3,...,9.7,9.9,8.2,2.6,4.7,8.1,0,High,195.6,43.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,27,26296.0,Bachelor,Urban,37.4,211.4,Sedan,0.0,314.8,10.0,...,9.9,6.6,8.9,5.1,7.8,9.3,1,High,162.5,37.5
49996,39,35476.0,Master,Suburban,30.5,158.3,Sedan,2.8,278.5,7.5,...,8.7,6.0,9.4,3.8,2.0,8.8,0,High,129.6,11.9
49997,30,20862.0,Master,Suburban,37.5,295.2,Sedan,0.0,358.4,7.7,...,7.3,6.6,4.5,5.2,1.3,5.9,0,High,218.3,52.8
49998,68,14694.0,Bachelor,Rural,40.3,256.5,Sedan,6.0,306.1,2.7,...,8.3,3.8,6.6,4.7,5.4,9.3,0,High,216.0,50.3
49999,48,28828.0,Bachelor,Suburban,28.5,192.6,Sedan,2.5,227.5,8.9,...,4.6,7.2,6.1,6.5,4.1,5.8,0,Medium,136.0,13.7

In [15]:
#5. If duplicates exist, drop them with .drop_duplicates() and report the new row count. If .duplicated().sum() is 0, explain why that makes sense for this dataset.
df=df.drop_duplicates()
print(f"There are {df.duplicated().sum()} in this data sense and this makes sense because it means the dataset has no exact row duplicates. This makes sense if the data inherently represents unique, independent events and features a strict primary key or timestamp.")

There are 0 in this data sense and this makes sense because it means the dataset has no exact row duplicates. This makes sense if the data inherently represents unique, independent events and features a strict primary key or timestamp.

In [17]:
#6. Create a new column commute_to_travel_ratio = daily_commute_km / weekly_travel_distance_km.
df["commute_to_travel_ratio"] = df.daily_commute_km / df.weekly_travel_distance_km
df.commute_to_travel_ratio.head()

0    0.193486
1    0.158425
2    0.171638
3    0.136852
4    0.186477
Name: commute_to_travel_ratio, dtype: float64

In [18]:
#7. What is the average value of this new ratio column(commute_to_travel_ratio)?
print(f"The average value of commute_to_travel_ratio is {df.commute_to_travel_ratio.mean()}")

The average value of commute_to_travel_ratio is 0.15655838853633144

In [19]:
#8. Round annual_income to the nearest thousand and store it in a new column income_rounded.
df["income_rounded"] = df.annual_income.round(-3)
df[["annual_income","income_rounded"]].head()

   annual_income  income_rounded
0        23019.0         23000.0
1        26440.0         26000.0
2        57167.0         57000.0
3        15841.0         16000.0
4        51571.0         52000.0

In [20]:
#9. What is the .mode() of current_vehicle_type — the single most common vehicle type?
df.current_vehicle_type.mode()

0    Sedan
Name: current_vehicle_type, dtype: object

In [21]:
#10. Use .min() and .max() together on age to get the age range in one line.
df.age.agg([min,max])

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_46916/455887465.py:2: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.age.agg([min,max])
/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_46916/455887465.py:2: FutureWarning: The provided callable <built-in function max> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.age.agg([min,max])

min    21
max    69
Name: age, dtype: int64

In [23]:
#11. Are there any rows where fuel_expense_per_month is negative? Use .any() on a boolean condition to check in one line
has_negative = (df["fuel_expense_per_month"] < 0).any()
has_negative

np.True_

In [24]:
#12. How many columns in the dataframe are entirely numeric? Use select_dtypes().
numeric_cols_count = len(df.select_dtypes(include='number').columns)
print(numeric_cols_count)

21

In [29]:
#13. On a copy of the dataframe, set city_type as the index using .set_index(). What changes about how the dataframe looks?
new_df = df.copy()
new_df = new_df.set_index("city_type")
new_df.head()

,age,annual_income,education_level,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,nearest_charging_station_km,...,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost,commute_to_travel_ratio,income_rounded
city_type,,,,,,,,,,,,,,,,,,,,,
Suburban,56,23019.0,High School,39.8,205.7,Hatchback,6.1,317.1,3.9,9.5,...,5.2,4.6,3.5,6.9,0,High,199.8,28.5,0.193486,23000.0
Suburban,46,26440.0,High School,34.6,218.4,Sedan,4.4,290.0,4.5,11.6,...,5.7,5.5,7.4,6.9,1,High,139.8,22.9,0.158425,26000.0
Suburban,46,57167.0,PhD,30.5,177.7,Sedan,0.4,201.4,6.3,6.4,...,7.8,5.3,6.2,6.8,0,High,158.0,38.5,0.171638,57000.0
Suburban,23,15841.0,Master,44.6,325.9,SUV,0.0,407.3,5.2,8.8,...,5.1,7.9,5.7,7.2,0,Low,207.0,45.0,0.136852,16000.0
Urban,50,51571.0,Master,52.4,281.0,SUV,5.2,458.4,4.3,0.5,...,8.2,2.6,4.7,8.1,0,High,195.6,43.9,0.186477,52000.0

In [30]:
#14. Reset that index back to default using .reset_index().
new_df = new_df.reset_index()
new_df.head()

,city_type,age,annual_income,education_level,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost,commute_to_travel_ratio,income_rounded
0,Suburban,56,23019.0,High School,39.8,205.7,Hatchback,6.1,317.1,3.9,...,5.2,4.6,3.5,6.9,0,High,199.8,28.5,0.193486,23000.0
1,Suburban,46,26440.0,High School,34.6,218.4,Sedan,4.4,290.0,4.5,...,5.7,5.5,7.4,6.9,1,High,139.8,22.9,0.158425,26000.0
2,Suburban,46,57167.0,PhD,30.5,177.7,Sedan,0.4,201.4,6.3,...,7.8,5.3,6.2,6.8,0,High,158.0,38.5,0.171638,57000.0
3,Suburban,23,15841.0,Master,44.6,325.9,SUV,0.0,407.3,5.2,...,5.1,7.9,5.7,7.2,0,Low,207.0,45.0,0.136852,16000.0
4,Urban,50,51571.0,Master,52.4,281.0,SUV,5.2,458.4,4.3,...,8.2,2.6,4.7,8.1,0,High,195.6,43.9,0.186477,52000.0

In [33]:
#16. Use .sample(5) to randomly pick 5 rows. Run the cell twice — do you get the same rows both times?
df.sample(5)

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost,commute_to_travel_ratio,income_rounded
45316,41,23742.0,Bachelor,Suburban,13.4,69.6,Hatchback,9.8,133.8,8.1,...,5.6,4.3,4.9,5.7,0,High,53.1,10.4,0.192529,24000.0
32378,50,12697.0,High School,Rural,25.5,171.2,Hatchback,5.1,152.1,6.6,...,4.6,10.0,4.0,5.9,0,Low,149.8,33.8,0.148949,13000.0
29405,56,32293.0,High School,Suburban,18.1,138.3,Sedan,3.0,157.3,9.5,...,8.0,2.7,5.1,8.7,1,High,100.6,25.1,0.130875,32000.0
45908,30,29360.0,Bachelor,Suburban,39.6,204.8,SUV,5.7,321.2,5.8,...,5.4,5.1,1.4,6.2,0,High,153.7,28.8,0.193359,29000.0
32614,31,31803.0,Bachelor,Suburban,38.8,294.6,Hatchback,11.6,271.2,5.0,...,7.7,3.7,5.6,7.9,0,High,183.5,41.4,0.131704,32000.0

In [37]:
#17. Now use .sample(5, random_state=42). Run it twice — are the rows identical now? Why does that happen?
print(df.sample(5, random_state=42))
print('This happens because random_state=42 sets a seed for the pseudo-random number generator. By fixing this seed, the sequence of "random" numbers generated is locked in, making the sampling operation reproducible across multiple runs.')

       age  annual_income education_level city_type  daily_commute_km  \
33553   67        35013.0          Master  Suburban              46.0
9427    49        43084.0          Master  Suburban              31.5
199     22        10380.0        Bachelor     Urban              16.7
12447   69        63274.0        Bachelor  Suburban              37.3
39489   58        25859.0          Master     Urban              16.5

       weekly_travel_distance_km current_vehicle_type  vehicle_age_years  \
33553                      330.1                  SUV                6.8
9427                       223.9                  SUV                4.9
199                         85.5                  SUV               11.1
12447                      264.7                Sedan                5.9
39489                       97.5                Sedan                3.7

       fuel_expense_per_month  charging_station_accessibility  ...  \
33553                   462.2                             1.7  ...
9427                    214.6                             4.2  ...
199                     214.0                             4.5  ...
12447                   302.5                             6.1  ...
39489                   138.0                             7.9  ...

       technology_affinity_score  range_anxiety_score  \
33553                        4.5                  5.6
9427                         5.6                  4.3
199                          5.2                  9.7
12447                        9.3                  2.4
39489                        7.5                  3.0

       battery_replacement_concern  ev_knowledge_score  \
33553                          3.9                 4.4
9427                           3.9                 5.9
199                            4.3                 6.2
12447                          3.6                 8.7
39489                          6.2                 8.6

       previous_ev_experience  ev_adoption_likelihood  \
33553                       1                  Medium
9427                        0                  Medium
199                         0                  Medium
12447                       0                    High
39489                       0                    High

       monthly_energy_consumption_kwh  monthly_charging_cost  \
33553                           282.8                   65.9
9427                            180.2                   37.1
199                              61.9                   11.1
12447                           198.3                   30.8
39489                            70.1                    8.6

       commute_to_travel_ratio  income_rounded
33553                 0.139352         35000.0
9427                  0.140688         43000.0
199                   0.195322         10000.0
12447                 0.140914         63000.0
39489                 0.169231         26000.0

[5 rows x 25 columns]
This happens because random_state=42 sets a seed for the pseudo-random number generator. By fixing this seed, the sequence of "random" numbers generated is locked in, making the sampling operation reproducible across multiple runs.

In [38]:
#18. Use .clip(lower=0) on fuel_expense_per_month to fix any negative values. How many rows actually changed?
df.fuel_expense_per_month.clip(lower=0)

0        317.1
1        290.0
2        201.4
3        407.3
4        458.4
         ...
49995    314.8
49996    278.5
49997    358.4
49998    306.1
49999    227.5
Name: fuel_expense_per_month, Length: 50000, dtype: float64

In [40]:
original = df['fuel_expense_per_month']
clipped = df['fuel_expense_per_month'].clip(lower=0)
original.sum(),clipped.sum()

(np.float64(14758480.399999999), np.float64(14763631.600000001))