In [12]:
import pandas as pd

orders = pd.DataFrame({
    "customer": ["A","A","B","B","C","A","C","D"],
    "product": ["Laptop","Mouse","Laptop","Keyboard","Mouse","Keyboard","Laptop","Monitor"],
    "amount": [800,20,900,50,25,70,850,300]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Find the total amount spent by each customer.
display(orders.groupby('customer')['amount'].sum())
# 2. Find the average purchase amount.
display(orders.groupby('customer')['amount'].mean())
# 3. Find the highest purchase amount.
display(orders.groupby('customer')['amount'].max())
# 4. Find the number of purchases.
display(orders.groupby('customer')['amount'].count())
# 5. Use agg() to calculate all the above in one statement.
display(orders.groupby('customer').agg(total_purchase_amount=('amount','sum'),
                                                 avg_purchase_amount=('amount','mean'),
                                                highest_purchase_amount=('amount','max'),
                                                 number_of_purchases=('amount','count')))

customer
A    890
B    950
C    875
D    300
Name: amount, dtype: int64

customer
A    296.666667
B    475.000000
C    437.500000
D    300.000000
Name: amount, dtype: float64

customer
A    800
B    900
C    850
D    300
Name: amount, dtype: int64

customer
A    3
B    2
C    2
D    1
Name: amount, dtype: int64

,total_purchase_amount,avg_purchase_amount,highest_purchase_amount,number_of_purchases
customer,,,,
A,890,296.666667,800,3
B,950,475.000000,900,2
C,875,437.500000,850,2
D,300,300.000000,300,1

In [15]:
import pandas as pd

sales = pd.DataFrame({
    "employee":["John","John","Alice","Alice","Bob","Bob"],
    "sales":[100,150,200,250,300,100]
})

# ==============================
# QUESTIONS
# ==============================

# Without reducing the number of rows:

# 1. Create a column containing total sales for each employee.
sales['total_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('sum')
# 2. Create a column containing average sales.
sales['avg_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('mean')
# 3. Create a column containing maximum sales.
sales['max_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('max')
# 4. Create a column containing transaction count.
sales['no_of_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('count')
# 5. Sort by total sales.
display(sales.sort_values(by="total_sales_of_each_employee",ascending=False))

,employee,sales,total_sales_of_each_employee,avg_sales_of_each_employee,max_sales_of_each_employee,no_of_sales_of_each_employee
2,Alice,200,450,225.0,250,2
3,Alice,250,450,225.0,250,2
4,Bob,300,400,200.0,300,2
5,Bob,100,400,200.0,300,2
0,John,100,250,125.0,150,2
1,John,150,250,125.0,150,2