In [8]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "IT", "HR", "Finance", "Finance"],
    "Salary": [50000, 70000, 80000, 55000, 90000, 85000]
})
"""
Task

Create a pivot table showing:

Department	Average Salary"""
pt1 = pd.pivot_table(df,index="Department",values='Salary',aggfunc='mean')
pt1

             Salary
Department
Finance     87500.0
HR          52500.0
IT          75000.0

In [10]:
df = pd.DataFrame({
    "Region": ["North","North","South","South","East","East"],
    "Product": ["Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "Sales": [100,80,120,90,150,110]
})
"""Task

Create a pivot table like

Region	Laptop	Phone
East	?	?
North	?	?
South	?	?

using the sum of sales."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc='sum')
pt

Product  Laptop  Phone
Region
East        150    110
North       100     80
South       120     90

In [16]:
#Exercise 3: Average Marks by Class and Subject (Medium)
df = pd.DataFrame({
    "Student":["A","B","C","D","E","F"],
    "Class":["10","10","10","9","9","9"],
    "Subject":["Math","Science","Math","Science","Math","Science"],
    "Marks":[88,75,92,81,95,78]
})
pt = pd.pivot_table(df,index='Class',columns='Subject',values='Marks',aggfunc='mean')
display(pt)

Subject  Math  Science
Class
10       90.0     75.0
9        95.0     79.5

In [30]:
#Exercise 4: Monthly Revenue Report (Medium)
df = pd.DataFrame({
    "Month":["Jan","Jan","Jan","Feb","Feb","Mar","Mar"],
    "Category":["Food","Electronics","Food","Food","Electronics","Food","Electronics"],
    "Revenue":[5000,12000,4000,6000,15000,7000,18000]
})
pt = pd.pivot_table(df,index='Month',columns='Category',values='Revenue',aggfunc='sum',fill_value=0)
display(pt)

Category  Electronics  Food
Month
Feb             15000  6000
Jan             12000  9000
Mar             18000  7000

In [25]:
#Exercise 5: Company Sales Dashboard (Medium)
df = pd.DataFrame({
    "Region":["North","North","North","South","South","East","East","East"],
    "Salesperson":["John","John","Mike","Mike","Sara","Sara","John","Mike"],
    "Product":["Laptop","Phone","Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "Sales":[100,150,120,170,200,180,110,140]
})
"""
Tasks
Part A

Create a pivot table showing

| Region | Total Sales |
"""
pt = pd.pivot_table(df,index='Region',values='Sales',aggfunc='sum')
pt = pt.rename(columns={'Sales':'Total Sales'})
pt

        Total Sales
Region
East            430
North           370
South           370

In [19]:
"""Part B

Create a pivot table

| Region | Laptop | Phone |

using sum."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc='sum')
pt

Product  Laptop  Phone
Region
East        110    320
North       220    150
South       200    170

In [20]:
"""Part C

Create a pivot table

| Salesperson | Average Sales |"""
pt = pd.pivot_table(df,index='Salesperson',values='Sales',aggfunc="mean")
pt

                  Sales
Salesperson
John         120.000000
Mike         143.333333
Sara         190.000000

In [24]:
"""Part D (Challenge)

Create a pivot table

| Region | Laptop Sales | Phone Sales | Grand Total |

using margins."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc="sum",margins=True, 
    margins_name='Grand Total')
pt = pt.rename(columns={
    'Laptop': 'Laptop Sales',
    'Phone': 'Phone Sales'
})
pt.columns.name = None
pt

             Laptop Sales  Phone Sales  Grand Total
Region
East                  110          320          430
North                 220          150          370
South                 200          170          370
Grand Total           530          640         1170

In [26]:
df = pd.DataFrame({
    "Department":["IT","IT","IT","HR","HR","Finance","Finance"],
    "Gender":["M","F","M","F","M","F","M"],
    "Experience":[2,4,5,3,6,7,5],
    "Salary":[60000,75000,80000,50000,65000,90000,85000]
})

Create a pivot table that shows:

Rows → Department
Columns → Gender
Values → Salary
Aggregation → Average salary

Then extend it to show both:

Average Salary
Maximum Salary

using a single pivot table.

In [27]:
pt = pd.pivot_table(df,index='Department',columns='Gender',values='Salary',aggfunc=["mean",'max'])
pt

               mean             max
Gender            F        M      F      M
Department
Finance     90000.0  85000.0  90000  85000
HR          50000.0  65000.0  50000  65000
IT          75000.0  70000.0  75000  80000

In [35]:
#Problem 1: Retail Store Sales Report ⭐ (Easy)
#Dataset
import pandas as pd

df = pd.DataFrame({
    "Store": ["A","A","A","B","B","B","C","C"],
    "Product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop","Phone"],
    "Sales": [120000,50000,30000,90000,60000,25000,100000,55000]
})
"""Business Requirement

The regional manager wants to compare how much revenue each store generated from each product.

Expected Output

          Laptop   Phone   Tablet
Store
A
B
C"""

pt = pd.pivot_table(df,index='Store',columns='Product',values='Sales',aggfunc='sum',fill_value=0)
pt

Product  Laptop  Phone  Tablet
Store
A        120000  50000   30000
B         90000  60000   25000
C        100000  55000       0

In [37]:
#Problem 2: Employee Performance Dashboard ⭐⭐
#Dataset
df = pd.DataFrame({
    "Employee":["Alice","Bob","Alice","Bob","Charlie","Charlie","Alice","Bob"],
    "Quarter":["Q1","Q1","Q2","Q2","Q1","Q2","Q3","Q3"],
    "Sales":[25,18,30,22,28,35,40,32]
})
"""Business Requirement

The HR team wants to know the average quarterly sales made by each employee.

Design a report where each employee is a row and each quarter is a separate column."""
pt = pd.pivot_table(df,index='Employee',columns='Quarter',values='Sales',aggfunc='mean',fill_value=0)
pt

Quarter     Q1    Q2    Q3
Employee
Alice     25.0  30.0  40.0
Bob       18.0  22.0  32.0
Charlie   28.0  35.0   0.0

In [41]:
#Problem 3: Hospital Patient Analytics ⭐⭐⭐
#Dataset
df = pd.DataFrame({
    "Department":["Cardiology","Cardiology","Neurology","Neurology","Orthopedic","Orthopedic","Cardiology","Neurology"],
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female"],
    "Age":[62,58,45,50,38,41,70,55]
})
"""Business Requirement

The hospital administrator wants to compare the average age of patients by department and gender.

Bonus

Also display the oldest patient in every department-gender combination."""
pt = pd.pivot_table(df,index='Department',columns='Gender',values='Age',aggfunc=['mean','max'])
pt

             mean          max
Gender     Female  Male Female Male
Department
Cardiology   58.0  66.0     58   70
Neurology    52.5  45.0     55   45
Orthopedic   41.0  38.0     41   38

In [43]:
#Problem 4: E-commerce Analytics ⭐⭐⭐
#Dataset
df = pd.DataFrame({
    "Month":["Jan","Jan","Jan","Feb","Feb","Mar","Mar","Mar","Apr"],
    "Category":["Electronics","Furniture","Clothing",
                "Electronics","Furniture",
                "Electronics","Furniture","Clothing",
                "Electronics"],
    "Orders":[120,60,90,140,70,160,80,100,180]
})
"""Business Requirement

The CEO wants a dashboard showing the total number of orders placed for each product category every month.

Bonus

If a category has no orders in a month, show 0 instead of NaN."""
pt= pd.pivot_table(df,index='Month',columns='Category',values='Orders',aggfunc='sum',fill_value=0)
pt

Category  Clothing  Electronics  Furniture
Month
Apr              0          180          0
Feb              0          140         70
Jan             90          120         60
Mar            100          160         80