In [8]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "IT", "HR", "Finance", "Finance"],
    "Salary": [50000, 70000, 80000, 55000, 90000, 85000]
})
"""
Task

Create a pivot table showing:

Department	Average Salary"""
pt1 = pd.pivot_table(df,index="Department",values='Salary',aggfunc='mean')
pt1

             Salary
Department
Finance     87500.0
HR          52500.0
IT          75000.0

In [10]:
df = pd.DataFrame({
    "Region": ["North","North","South","South","East","East"],
    "Product": ["Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "Sales": [100,80,120,90,150,110]
})
"""Task

Create a pivot table like

Region	Laptop	Phone
East	?	?
North	?	?
South	?	?

using the sum of sales."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc='sum')
pt

Product  Laptop  Phone
Region
East        150    110
North       100     80
South       120     90