In [4]:
import pandas as pd

# ==========================================================
# Problem 1: Regional Sales Dashboard
#
# Business Requirement:
#
# The CEO wants a dashboard showing:
#
# • Total Revenue
# • Average Revenue
#
# for every Region and Product combination.
#
# Missing combinations should display 0.
#
# Add Overall totals.
# ==========================================================

df = pd.DataFrame({
    "Region":["North","North","South","South","East","West","West","East"],
    "Product":["Laptop","Phone","Laptop","Tablet","Phone","Laptop","Phone","Tablet"],
    "Revenue":[120,80,140,100,90,150,70,110]
})

pt = pd.pivot_table(df,index='Region',columns='Product',values='Revenue',
                    aggfunc=['sum','mean'],fill_value=0).rename(columns={"sum":"Total Revenue","mean":"Average Revenue"})
pt

        Total Revenue              Average Revenue
Product        Laptop Phone Tablet          Laptop Phone Tablet
Region
East                0    90    110             0.0  90.0  110.0
North             120    80      0           120.0  80.0    0.0
South             140     0    100           140.0   0.0  100.0
West              150    70      0           150.0  70.0    0.0

In [7]:
import pandas as pd

# ==========================================================
# Problem 2: University Performance Report
#
# Business Requirement:
#
# Show:
#
# Average Marks
# Highest Marks
#
# for every Department and Semester.
#
# Display Semester as columns.
#
# ==========================================================

df = pd.DataFrame({
    "Department":["CSE","CSE","ECE","ECE","EEE","EEE","CSE","ECE"],
    "Semester":[1,2,1,2,1,2,2,1],
    "Marks":[82,91,76,88,80,94,95,84]
})

pt = pd.pivot_table(df,index='Department',columns='Semester',values='Marks',
                    aggfunc=['mean','max']).rename(columns={'mean':"Average Marks",'max':"Highest Mark"})
pt

           Average Marks       Highest Mark
Semester               1     2            1   2
Department
CSE                 82.0  93.0           82  95
ECE                 80.0  88.0           84  88
EEE                 80.0  94.0           80  94

In [8]:
import pandas as pd

# ==========================================================
# Problem 3: Employee Salary Dashboard
#
# Business Requirement:
#
# Show:
#
# Average Salary
# Maximum Salary
#
# grouped by
#
# Department
# Gender
#
# Include Overall totals.
#
# Rename the total row to Company Total.
# ==========================================================

df = pd.DataFrame({
    "Department":["IT","IT","HR","HR","Finance","Finance","IT"],
    "Gender":["M","F","M","F","M","F","F"],
    "Salary":[70000,82000,55000,62000,90000,95000,78000]
})

pt = pd.pivot_table(df,index="Department",columns='Gender',values='Salary',
                    aggfunc=['mean','max'],fill_value=0,
                    margins=True,margins_name="Company Total").rename(columns={"mean":"Average Salary",'max':'Maximum Salary'})
pt

              Average Salary                             Maximum Salary  \
Gender                     F             M Company Total              F
Department
Finance              95000.0  90000.000000  92500.000000          95000
HR                   62000.0  55000.000000  58500.000000          62000
IT                   80000.0  70000.000000  76666.666667          82000
Company Total        79250.0  71666.666667  76000.000000          95000


Gender             M Company Total
Department
Finance        90000         95000
HR             55000         62000
IT             70000         82000
Company Total  90000         95000

In [10]:
import pandas as pd

# ==========================================================
# Problem 4: Bank Transactions
#
# Business Requirement:
#
# Create a dashboard showing
#
# Total Transaction Amount
#
# Branch × Month × Transaction Type
#
# Replace missing values with 0.
#
# ==========================================================

df = pd.DataFrame({
    "Branch":["A","A","A","B","B","C","C","C"],
    "Month":["Jan","Feb","Feb","Jan","Feb","Jan","Feb","Mar"],
    "Type":["Deposit","Deposit","Withdrawal","Deposit",
            "Withdrawal","Deposit","Deposit","Withdrawal"],
    "Amount":[5000,7000,3000,8000,2000,9000,6000,4000]
})

pt = pd.pivot_table(df,index=['Branch','Month'],columns='Type',aggfunc='sum',fill_value=0)
pt

              Amount
Type         Deposit Withdrawal
Branch Month
A      Feb      7000       3000
       Jan      5000          0
B      Feb         0       2000
       Jan      8000          0
C      Feb      6000          0
       Jan      9000          0
       Mar         0       4000

In [17]:
import pandas as pd

# ==========================================================
# Problem 5: Retail Analytics
#
# Business Requirement:
#
# Build ONE pivot table showing:
#
# Rows:
# Store
#
# Columns:
# Product
# Year
#
# Values:
# Total Sales
#
# Include Overall totals.
#
# Replace missing values with 0.
# ==========================================================

df = pd.DataFrame({
    "Store":["A","A","A","B","B","C","C","A"],
    "Product":["Laptop","Phone","Tablet","Laptop","Phone","Laptop","Tablet","Laptop"],
    "Year":[2023,2023,2024,2024,2023,2023,2024,2024],
    "Sales":[120,80,90,150,100,140,110,170]
})

pt=pd.pivot_table(df,index='Store',columns=['Product','Year'],values ='Sales',aggfunc='sum',fill_value=0).rename(columns=
                                                                                                                 {'Laptop':'Total Laptop Sales',
                                                                                                                  'Phone':'Total Phone Sales',
                                                                                                                 'Tablet':'Total Tablet Sales'})
pt

Product Total Laptop Sales      Total Phone Sales Total Tablet Sales
Year                  2023 2024              2023               2024
Store
A                      120  170                80                 90
B                        0  150               100                  0
C                      140    0                 0                110

In [18]:
import pandas as pd

# ==========================================================
# Problem 6: Department Statistics
#
# Business Requirement:
#
# Calculate:
#
# Average Salary
# Highest Salary
# Lowest Salary
# Employee Count
#
# using one groupby().
# ==========================================================

df = pd.DataFrame({
    "Department":["IT","IT","HR","HR","Finance","Finance","Marketing"],
    "Salary":[70000,82000,55000,62000,90000,95000,65000]
})

df.groupby('Department').agg(**{"Average Salary":('Salary','mean'),
                               "Highest Salary":('Salary','max'),
                               "Lowest Salary":('Salary','min'),
                               "Employee Count":('Salary','count'),})

            Average Salary  Highest Salary  Lowest Salary  Employee Count
Department
Finance            92500.0           95000          90000               2
HR                 58500.0           62000          55000               2
IT                 76000.0           82000          70000               2
Marketing          65000.0           65000          65000               1

In [19]:
import pandas as pd

# ==========================================================
# Problem 7: Employee Contribution
#
# Business Requirement:
#
# Add a column
#
# Contribution (%)
#
# showing each employee's contribution
# to department sales.
#
# ==========================================================

df = pd.DataFrame({
    "Employee":["A","B","C","D","E","F","G"],
    "Department":["IT","IT","IT","HR","HR","Finance","Finance"],
    "Sales":[20,30,50,40,60,90,110]
})

dept_total = df.groupby('Department')['Sales'].transform('sum')
df['Contribution (%)'] = (df['Sales'] / dept_total) * 100
df

  Employee Department  Sales  Contribution (%)
0        A         IT     20              20.0
1        B         IT     30              30.0
2        C         IT     50              50.0
3        D         HR     40              40.0
4        E         HR     60              60.0
5        F    Finance     90              45.0
6        G    Finance    110              55.0

In [21]:
import pandas as pd

# ==========================================================
# Problem 8: Best Employee
#
# Business Requirement:
#
# Return ONLY the highest paid employee
# from every department.
#
# Return complete rows.
#
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank","George"],
    "Department":["IT","IT","HR","HR","Finance","Finance","IT"],
    "Salary":[70000,92000,55000,62000,85000,98000,88000]
})

df.loc[df.groupby('Department')['Salary'].idxmax()]

  Employee Department  Salary
5    Frank    Finance   98000
3    David         HR   62000
1      Bob         IT   92000

In [22]:
import pandas as pd

# ==========================================================
# Problem 9: Employee Ranking
#
# Business Requirement:
#
# Add TWO new columns:
#
# Department Rank
# Overall Rank
#
# Highest salary should receive Rank 1.
#
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank","George"],
    "Department":["IT","IT","HR","HR","Finance","Finance","IT"],
    "Salary":[70000,92000,55000,62000,85000,98000,88000]
})

df["Rank"] = (df.groupby('Department')['Salary'].rank(ascending=False,method='dense'))
df

  Employee Department  Salary  Rank
0    Alice         IT   70000   3.0
1      Bob         IT   92000   1.0
2  Charlie         HR   55000   2.0
3    David         HR   62000   1.0
4      Eva    Finance   85000   2.0
5    Frank    Finance   98000   1.0
6   George         IT   88000   2.0

In [24]:
import pandas as pd

# ==========================================================
# Problem 10: Advanced GroupBy
#
# Business Requirement:
#
# Return ONLY departments
# whose average salary
# is greater than 80,000.
#
# Then:
#
# Add a column containing
# department average salary.
#
# Add another column
# ranking employees
# within that department.
#
# Return all employees
# belonging to those departments.
#
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David",
                "Eva","Frank","George","Helen"],
    "Department":["IT","IT","HR","HR",
                  "Finance","Finance","Marketing","Marketing"],
    "Salary":[70000,92000,55000,62000,
              85000,98000,60000,95000]
})

df['Average salary'] = df.groupby('Department')['Salary'].transform('mean')
df["Rank"] = (df.groupby('Department')['Salary'].rank(ascending=False,method='dense'))
df[df['Average salary'] > 80000]['Department']

0         IT
1         IT
4    Finance
5    Finance
Name: Department, dtype: object