In [4]:
import pandas as pd

# ==========================================================
# Problem 1: Regional Sales Dashboard
#
# Business Requirement:
#
# The CEO wants a dashboard showing:
#
# • Total Revenue
# • Average Revenue
#
# for every Region and Product combination.
#
# Missing combinations should display 0.
#
# Add Overall totals.
# ==========================================================

df = pd.DataFrame({
    "Region":["North","North","South","South","East","West","West","East"],
    "Product":["Laptop","Phone","Laptop","Tablet","Phone","Laptop","Phone","Tablet"],
    "Revenue":[120,80,140,100,90,150,70,110]
})

pt = pd.pivot_table(df,index='Region',columns='Product',values='Revenue',
                    aggfunc=['sum','mean'],fill_value=0).rename(columns={"sum":"Total Revenue","mean":"Average Revenue"})
pt

        Total Revenue              Average Revenue
Product        Laptop Phone Tablet          Laptop Phone Tablet
Region
East                0    90    110             0.0  90.0  110.0
North             120    80      0           120.0  80.0    0.0
South             140     0    100           140.0   0.0  100.0
West              150    70      0           150.0  70.0    0.0

In [7]:
import pandas as pd

# ==========================================================
# Problem 2: University Performance Report
#
# Business Requirement:
#
# Show:
#
# Average Marks
# Highest Marks
#
# for every Department and Semester.
#
# Display Semester as columns.
#
# ==========================================================

df = pd.DataFrame({
    "Department":["CSE","CSE","ECE","ECE","EEE","EEE","CSE","ECE"],
    "Semester":[1,2,1,2,1,2,2,1],
    "Marks":[82,91,76,88,80,94,95,84]
})

pt = pd.pivot_table(df,index='Department',columns='Semester',values='Marks',
                    aggfunc=['mean','max']).rename(columns={'mean':"Average Marks",'max':"Highest Mark"})
pt

           Average Marks       Highest Mark
Semester               1     2            1   2
Department
CSE                 82.0  93.0           82  95
ECE                 80.0  88.0           84  88
EEE                 80.0  94.0           80  94